### ISSUE TITLE
v2ray更新

### ISSUE THREAD

**Issue by updater1234** [wulabing/V2Ray_ws-tls_bash_onekey#1]
你好，如果v2ray发布新版本，那么如何更新？

**Comment by wulabing** [comment]
哇。这个问题我还没有想过，不过安装用的是官方的安装脚本，所以按道理来说，可以直接用官方脚本的更新方式进行更新。我会在稍后阶段做一下测试。您也可以自行测试。

**Comment by wulabing** [comment]
已完善相关内容，请参看readme
