### ISSUE TITLE
这不是一个issue。大赞V3.0版本

### ISSUE THREAD

**Issue by nemo5175747** [wulabing/V2Ray_ws-tls_bash_onekey#10]
V3版直接可以套CF了， SSL 用strict，上一个版本一直不行我以为是我的CF 配置不对。
然后web页面换上了可爱的计算器。
性能还没多测试但是至少已经work。
大赞！

**Comment by nemo5175747** [comment]
自我更新一下。
估计是刚才操作太快了，CF添加的时候用DNS直接解析，未用他的CDN。一切正常。
启动CDN估计等的时间不够，事实并没有应用到网络上。后面发现启动CDN还是不能工作。
不知道 @wulabing 有没有测试套用CF是否可以工作？能否把CF 里面的 Crypto页配置说一下？
谢谢！

**Comment by wulabing** [comment]
统一至 #11
