### ISSUE TITLE
nginx不能开机启动

### ISSUE THREAD

**Issue by tueac** [wulabing/V2Ray_ws-tls_bash_onekey#100]
centos7使用脚本安装ws+tls+nginx后，如果重启服务器，nginx并不会开机自启，在rc.loac文件中也看到开机自启命令项，需要手动运行启动命令才能启动。

**Comment by wulabing** [comment]
已收到反馈

tueac <notifications@github.com> 于 2019年10月17日周四 09:30写道：

**Comment by liubo20190515** [comment]
Failed to start The NGINX HTTP and reverse proxy server.
vps重启后经常这样，需要restart才能恢复正常
