### ISSUE TITLE
nignx需要做相应防护么，/etc/nigix/log error.log看到大量的请求记录有点担心

### ISSUE THREAD

**Issue by November-raining** [wulabing/V2Ray_ws-tls_bash_onekey#105]
首先感谢脚本，看访问日志部分内容如下
2019/10/19 09:23:33 [error] 21295#0: *902 open() "/home/wwwroot/levis/cn" failed (2: No such file or directory), client:******
2019/10/19 09:23:39 [error] 21295#0: *903 "/home/wwwroot/levis/support/troubleshooting/china-status/index.html" is not found (2: No such file or directory), client: ******
2019/10/19 09:23:44 [error] 21295#0: *902 open() "/home/wwwroot/levis/vpn-software/vpn-windows" failed (2: No such file or directory), client: ****** 
2019/10/19 10:12:16 [error] 21295#0: *1051 open() "/home/wwwroot/levis/cn" failed (2: No such file or directory), ****** 
2019/10/19 10:12:23 [error] 21295#0: *1052 open() "/home/wwwroot/levis/support/troubleshooting" failed (2: No such file or directory), client: ****** 
2019/10/19 10:12:27 [error] 21295#0: *1053 open() "/home/wwwroot/levis/support/troubleshooting/china-status" failed (2: No such file or directory), ****** 
2019/10/19 11:50:08 [error] 21295#0: *1241 open() "/etc/nginx/html/mysql/admin/index.php" failed (2: No such file or directory),****** 
2019/10/19 11:50:09 [error] 21295#0: *1242 open() "/etc/nginx/html/mysql/dbadmin/index.php" failed (2: No such file or directory),****** 
2019/10/19 11:50:10 [error] 21295#0: *1243 open() "/etc/nginx/html/mysql/sqlmanager/index.php" failed (2: No such file or directory), ****** 
2019/10/19 11:50:10 [error] 21295#0: *1244 open() "/etc/nginx/html/mysql/mysqlmanager/index.php" failed (2: No such file or directory), ****** 

是否要做些安全防护什么的或者说不用，服务器端有fail2ban保护ssh，还请指点一二

**Comment by wulabing** [comment]
页面仅用于所谓的伪装，不需要做防护

**Comment by November-raining** [comment]
好的
