### ISSUE TITLE
怎么更新脚本比较好

### ISSUE THREAD

**Issue by LDQ-first** [wulabing/V2Ray_ws-tls_bash_onekey#106]
已经安装过旧版的脚本，怎么更新比较好？

**Comment by wulabing** [comment]
如果不能重装系统，你可以通过删除以下文件夹，重新安装来完成更新
/etc/nginx
/etc/v2ray
/root/v2ray
~/.acme.sh

**Comment by yinhaibo01** [comment]
这样就把用户配置文件也删除了吧？可以如果脚本可以检测 已经存在nginx和v2ray配置文件，备份一下，然后删除从新安装，再恢复配置文件，就完美啦。不过呢，也看老大您的心情啦  : )
