### ISSUE TITLE
原先装了LNMP的环境下，安装这个脚本会冲突吗？

### ISSUE THREAD

**Issue by hkbbdx** [wulabing/V2Ray_ws-tls_bash_onekey#109]
RT

**Comment by hkbbdx** [comment]
我现在安装的是appnode面板，装的是lnmp环境。

**Comment by wulabing** [comment]
我不太清楚appnode的默认目录，可能会冲突，请根据wiki提供的相关路径判断是否冲突

**Comment by hkbbdx** [comment]
Nginx
主程序路径：/usr/sbin/nginx
配置文件路径：/etc/nginx.conf
