### ISSUE TITLE
Cloudflare 嵌套问题

### ISSUE THREAD

**Issue by nemo5175747** [wulabing/V2Ray_ws-tls_bash_onekey#11]
用CF 嵌套之后，小计算器显示不正常了，不知道是不是证书问题？
其他都不影响，强迫症驱使哈
![image](https://user-images.githubusercontent.com/18659424/37329742-d9d75bfe-26d9-11e8-8310-2c7cc1a889fd.png)

**Comment by wulabing** [comment]
本脚本不建议使用cf进行嵌套。（当你的ip没有被墙时，完全不需要，并且非常非常非常非常非常不建议使用cloudflare的cdn功能，因为不但不会加速，还会减速）
这是因为 websocket 和 tls 部分的实现 都已经在服务端完成了
如果一定要使用cf的嵌套，并且让 cf 来实现tls部分，那么你需要对服务端的nginx配置进行如下修改
* 删除nginx的 ssl 相关字段
* 删除 301 重定向部分
* 修改监听端口 为 80 端口

**Comment by wulabing** [comment]
至于显示不正常的原因，这个不太清楚，看起来像是css的加载问题，你可以开启chrome的开发者工具来排除相关问题。毕竟这只是个单纯的伪装，我是随便挑了一个开源代码拿过来用的O(∩_∩)O

**Comment by nemo5175747** [comment]
非常感谢回复。
加cf不是为了加速，是为了保护ip不被发现。其实也是觉得好玩，反正用的是google的云，重启一下vps就换ip了。
已经说明了这个脚本不建议用cf，那就明白了。尊重这个脚本的使用策略。
谢谢！

**Comment by wulabing** [comment]
我使用我自己的2.0版本，那个时候伪装路径还不是随机，并且没有页面伪装，依然成功通过了8次GFW的封禁（从除夕前一直到此时此刻，那台服务器从使用到现在 GFW 一共就封过8轮），此次更新实际上只是个大版本完善过程，关于套用CDN的部分，对脚本稍作修改即可实现，有时间的话我会进行一下适配，使脚本同时提供 完全一键配置 和 使用cdn加速 的配置

* 注：降低封禁概率的方法就是完全删除ssr服务端，转而使用 V2ray三件套 或 ss-libev

**Comment by nemo5175747** [comment]
多谢提醒。
讲真的你没有感觉在同等条件下，ss比vmess快很多么？
同等条件指的是同一台服务器，同一个客户端，客户端网络不变且比较稳定的时段，然后用fast.com测3次平均。
我的感觉ss是vmess速度是10倍。

**Comment by wulabing** [comment]
你可以尝试开启mux多路复用之后再进行一次测试（我也不太清楚这东西和测速有没有关系），但是在实际使用上，我没有感觉两者的速度差距有多少，不过如果真的比ss慢，也不是没有道理，毕竟nginx websocket tls 这一折腾多，通讯起来多了一些流程

**Comment by nemo5175747** [comment]
我在最初测试的时候用的纯vmess，没有tls和ws，也是一样。不过我有新感觉。我上面说的测试客户端用的iOS小火箭和win下面的官方客户端。
刚刚有机会在我的mac上用，同样用官方的客户端包括ss和v2再测，速度相同。
所以感觉速度差异来自于客户端，不是服务器。小火箭不太清除，但是win下面的客户端应该对两者支持不会差那么远啊。
这个issue关闭了，免的跑题太远。
谢谢
