### ISSUE TITLE
解决 Path 分流的 Bad Request 问题

### ISSUE THREAD

**Issue by dylanbai8** [wulabing/V2Ray_ws-tls_bash_onekey#12]
解决 Path 分流的 Bad Request 问题

1.开启Bad Request错误跳转
vi /etc/nginx/nginx.conf
在代码http{}段里添加一句
proxy_intercept_errors on;

2.设置跳转页
vi /etc/nginx/conf.d/v2ray.conf
在443端口的配置里加一句
error_page 400 = /400.html;
跳转到400页面，或者直接跳转回首页。

**Comment by dylanbai8** [comment]
感谢推荐，代码文盲 胡乱拼凑的 见笑了！

**Comment by wulabing** [comment]
客气啦

不过我不太理解，什么时候会出现Bad Request的情况呢，我使用的时候貌似没遇到过，能解释一下么
