### ISSUE TITLE
域名申请证书过多导致证书生成失败

### ISSUE THREAD

**Issue by R-81** [wulabing/V2Ray_ws-tls_bash_onekey#122]
尝试了太多次，导致域名证书太多了，最后证书生成失败，请问有什么解决办法吗？谢谢

**Comment by wulabing** [comment]
换个子域名

R-81 <notifications@github.com> 于2019年11月20日周三 上午12:30写道：

**Comment by HUI2125281** [comment]
不是等等就行了么？
