### ISSUE TITLE
 重開機之後就無法連線

### ISSUE THREAD

**Issue by Harumi3020** [wulabing/V2Ray_ws-tls_bash_onekey#123]
大家好

我的情況如下：

1.	我已經正確的安裝好腳本，並且可以正常的”科學上網使用”，Win、IPhone、Android都可以，並且我套上了CF也OK沒問題

2.	我的環境是Centos 7 + WS + TLS + CF

問題點

1.	當我安裝好腳本，設定好之後，都沒問題
2.	當我”重新開機(我是自行架設的虛擬機，不是VPS)，用戶端完全連不上線，出現的錯誤就是 failed to handler mux client connection
3.	關掉用戶端 Mux 就出現Failed to process outbound traffic
，
但是當我”重新跑一次腳本，等於重新”安裝”一次之後，一模一樣的環境，就可以連線了…..

所以證明了幾點
1.	網路沒有任何斷流問題
2.	用戶端設定沒有任何問題
3.	Centos 環境本身也沒有任何問題

就是”重開機”所導致的…….
昨晚我一整晚都沒關機，然後到現在都還可以正常連線

因此想請各位大大是否能幫我抓看看問題會在哪邊，我可以實作一下
謝謝大家！

**Comment by wulabing** [comment]
有可能是重启机器以后，某个服务没有起来
可以在重启之后尝试分别启动 Nginx 和 V2ray

**Comment by Harumi3020** [comment]
> 有可能是重启机器以后，某个服务没有起来
> 可以在重启之后尝试分别启动 Nginx 和 V2ray

好~我現在測試，下午把測試情況繼續貼出來~

**Comment by Harumi3020** [comment]
經過比對，確實重開機之後需要  "手動" 重啟  Nginx 和 V2ray 的服務
這部分還請版主跟各位看看問題在哪裡了，謝謝大家！
