### ISSUE TITLE
问下大佬出现发生SSL错误，无法建立到服务器的安全连接。

### ISSUE THREAD

**Issue by LInJunYue** [wulabing/V2Ray_ws-tls_bash_onekey#126]
发生SSL错误，无法建立到服务器的安全连接。这是什么，有大佬能告诉下不

**Comment by lj407269507** [comment]
-- Logs begin at Wed 2019-06-19 15:01:12 CST, end at Sat 2019-11-23 15:53:39 CST. --
Nov 23 15:33:30 iZt4ngmjpjfqrfbdh6ux6rZ systemd[1]: Started V2Ray Service.
Nov 23 15:33:31 iZt4ngmjpjfqrfbdh6ux6rZ v2ray[16833]: V2Ray 4.21.3 (V2Fly, a community-driven edition of V2
Nov 23 15:33:31 iZt4ngmjpjfqrfbdh6ux6rZ v2ray[16833]: A unified platform for anti-censorship.
Nov 23 15:33:31 iZt4ngmjpjfqrfbdh6ux6rZ v2ray[16833]: main: failed to read config file: /etc/v2ray/config.j
Nov 23 15:33:31 iZt4ngmjpjfqrfbdh6ux6rZ v2ray[16833]: > exit status 255
Nov 23 15:33:31 iZt4ngmjpjfqrfbdh6ux6rZ systemd[1]: v2ray.service: main process exited, code=exited, status
Nov 23 15:33:31 iZt4ngmjpjfqrfbdh6ux6rZ systemd[1]: Unit v2ray.service entered failed state.
Nov 23 15:33:31 iZt4ngmjpjfqrfbdh6ux6rZ systemd[1]: v2ray.service failed.
-- Reboot --
Nov 23 15:38:24 iZt4ngmjpjfqrfbdh6ux6rZ systemd[1]: Started V2Ray Service.
Nov 23 15:38:25 iZt4ngmjpjfqrfbdh6ux6rZ v2ray[2864]: V2Ray 4.21.3 (V2Fly, a community-driven edition of V2R
Nov 23 15:38:25 iZt4ngmjpjfqrfbdh6ux6rZ v2ray[2864]: A unified platform for anti-censorship.
Nov 23 15:38:25 iZt4ngmjpjfqrfbdh6ux6rZ v2ray[2864]: main: failed to read config file: /etc/v2ray/config.js
Nov 23 15:38:25 iZt4ngmjpjfqrfbdh6ux6rZ v2ray[2864]: > exit status 255
Nov 23 15:38:25 iZt4ngmjpjfqrfbdh6ux6rZ systemd[1]: v2ray.service: main process exited, code=exited, status
Nov 23 15:38:25 iZt4ngmjpjfqrfbdh6ux6rZ systemd[1]: Unit v2ray.service entered failed state.
Nov 23 15:38:25 iZt4ngmjpjfqrfbdh6ux6rZ systemd[1]: v2ray.service failed.
lines 1-18/18 (END)
