### ISSUE TITLE
vps重启后，nginx起不来

### ISSUE THREAD

**Issue by liubo20190515** [wulabing/V2Ray_ws-tls_bash_onekey#127]
Failed to start The NGINX HTTP and reverse proxy server.
这样的报错。

**Comment by wulabing** [comment]
log信息不足
请自查80端口的占用情况

**Comment by cn-404-not-found** [comment]
重启后的确ngnix起不来，导致无法爬墙，需要手动启动ngnix，然后就正常了

**Comment by funray** [comment]
I encountered a similar situation recently and I solved it by installing [haveged](https://wiki.archlinux.org/index.php/Haveged)
#123 #100 @wulabing

**Comment by cn-404-not-found** [comment]
安装haveged后，重启的确可以自动启动nginx，算是个解决方案吧

**Comment by wulabing** [comment]
该依赖安装将添加到下个版本中，感谢

cn-404-not-found <notifications@github.com> 于2019年11月28日周四 下午4:42写道：
