### ISSUE TITLE
请问作者这是什么问题啊，其他的isuue方法都试过也没办法

### ISSUE THREAD

**Issue by NewGoals** [wulabing/V2Ray_ws-tls_bash_onekey#129]

**Comment by NewGoals** [comment]
[图片]

**Comment by NewGoals** [comment]
![Uploading {DZ7{[WQRRHCY$66$(OL4V2.png…]()

**Comment by NewGoals** [comment]
[Thu Nov 28 19:36:07 CST 2019] Standalone mode.
[Thu Nov 28 19:36:07 CST 2019] Single domain='newgoals.info'
[Thu Nov 28 19:36:07 CST 2019] Getting domain auth token for each domain
[Thu Nov 28 19:36:09 CST 2019] Getting webroot for domain='newgoals.info'
[Thu Nov 28 19:36:09 CST 2019] Verifying: newgoals.info
[Thu Nov 28 19:36:09 CST 2019] Standalone mode server
[Thu Nov 28 19:36:13 CST 2019] Pending
[Thu Nov 28 19:36:15 CST 2019] ****:Verify error:Fetching http://newgoals.info/.well-known/acme-challenge/fwFEb4i4p9lfEdUBCF6mF2Xm_TcmandBz6D-l9-4sik: Connection reset by peer
[Thu Nov 28 19:36:15 CST 2019] Please add '--debug' or '--log' to check more details.
[Thu Nov 28 19:36:15 CST 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[错误]  SSL 证书生成失败

**Comment by NewGoals** [comment]
> _No description provided._

**Comment by ChienHoWee** [comment]
我也遇到了，是端口没有开放，我也不知道是哪个端口，在防火墙中把所有端口打开就解决了。

**Comment by NewGoals** [comment]
> 我也遇到了，是端口没有开放，我也不知道是哪个端口，在防火墙中把所有端口打开就解决了。

脚本安装的时候不是把防火墙关闭了吗， 而且之前我也把443和80都打开了呀
