### ISSUE TITLE
有卸载方法，

### ISSUE THREAD

**Issue by chafer516** [wulabing/V2Ray_ws-tls_bash_onekey#130]
有卸载方法，

**Comment by chafer516** [comment]
不可以卸载吗

**Comment by WalkerInfinite** [comment]
好像没有，感觉有点坑

**Comment by wulabing** [comment]
有卸载方法，不过在使用方式中没有说明。

Infinite Walker <notifications@github.com> 于2019年12月10日周二 上午10:51写道：

**Comment by sad-castle** [comment]
怎么卸载

**Comment by wulabing** [comment]
wget -N
https://raw.githubusercontent.com/wulabing/V2Ray_ws-tls_bash_onekey/master/install.sh
&& bash ./install.sh uninstall

sad-castle <notifications@github.com> 于2019年12月11日周三 下午12:01写道：

**Comment by sad-castle** [comment]
get
