### ISSUE TITLE
楼主里面的nginx不支持IPV6，可以更新下版本吗？

### ISSUE THREAD

**Issue by spiketim188** [wulabing/V2Ray_ws-tls_bash_onekey#133]
楼主里面的nginx不支持IPV6，可以更新下版本吗？

**Comment by 2444989513** [comment]
自己加
listen [::]:80;
listen [::]:443 ssl http2;

**Comment by 2444989513** [comment]
![1578033431(1)](https://user-images.githubusercontent.com/56295510/71710309-94eea180-2e36-11ea-8104-84661bf27acf.png)
