### ISSUE TITLE
安装成功。但是用的阿里云的域名 好像不行啊。安装都是成功的。。大神指点一下

### ISSUE THREAD

**Issue by zmaibbs7** [wulabing/V2Ray_ws-tls_bash_onekey#14]
1、用的是阿里云的 .top域名 [便宜]
2、安装都是现实成功的。域名A记录绑定都是对的
是因为阿里云域名的关系吗？
域名进去后变成一个计算机在线的网页了

**Comment by zmaibbs7** [comment]
![default](https://user-images.githubusercontent.com/20255524/37555045-6f1f6252-2a1c-11e8-8947-5b42da17d5a9.JPG)

![1](https://user-images.githubusercontent.com/20255524/37555034-41ec8ee0-2a1c-11e8-8a0e-304cf36506e3.JPG)

**Comment by wulabing** [comment]
检查一下 复制域名地址的时候有没有多空格
其他的地方有没有多空格

**Comment by zmaibbs7** [comment]
谢谢 大佬回答。
我之前搭建的一个简单的v2ray用[V2RayW]这个软件可以用，但是用[v2rayN] 这个软件就不行了。用虚拟机试了下也不行。。我再试试。。晕。。
跪谢大佬。！！

**Comment by wulabing** [comment]
客户端那面更新一下内核，客户端内核太久服务端内核太新可能会导致无法连接

**Comment by zmaibbs7** [comment]
内核是：https://github.com/v2ray/v2ray-core/releases 最新版本
v2rayN是:https://github.com/2dust/v2rayN/releases 最新版本
这两个文件下载放到一起对吧。。类似V2RayW。V2RayW可以用以前我搭的简单的V2ray，用[v2rayN] 这个软件就不行了
彻底晕了。。

**Comment by wulabing** [comment]
可以开启log然后看看log信息。其他的我也帮不上什么，gce的防火墙要放开。

**Comment by zmaibbs7** [comment]
嗯。 谢谢 大佬。
防火墙都开了。我再多试试。。总有成功的一次。。。

**Comment by wulabing** [comment]
好 坚持不懈就是胜利。实在不行就重装一轮

**Comment by wulabing** [comment]
最近的GCE服务器都是瘫痪状态，应该是被攻击，整个网段都受影响了，所以可能不是配置的问题，你可以尝试换其他的服务器配置一下看看

**Comment by zmaibbs7** [comment]
嗯 嗯。。。好的。。虽然看不太懂。。应该是我的问题。感觉这个方案很高大上啊！

**Comment by zmaibbs7** [comment]
今天弄了10个小时。。
总结如下，简单配置的v2ray[不是本脚本的]用V2RayW可以正常使用，用v2rayN就不行。
仔细比较了下配置文件，发现格式不一样，差的很多。内核都是最新版本的。
目前解决不了。应该是v2rayN这个软件目前有点小问题
直接使用内核的话，这个配置文件实在太多，配置不来。
有大神的给个这个脚本的配置文件，我照着改下...
凄凄惨惨戚戚...

**Comment by wulabing** [comment]
我去更新一下我自己的版本，然后尝试一下看看是不是V2rayN的问题

**Comment by wulabing** [comment]
经过尝试最新版的内核配合最新版的V2rayN客户端是可以正常工作的

**Comment by zmaibbs7** [comment]
还是不行。SSR又能用了。。先用SSR吧。。
这个V2rayN不知道哪里问题。google几个操作说明，都是这样。
o(╥﹏╥)o

**Comment by zmaibbs7** [comment]
大神~ 
换了 搬瓦工就可以了。。可能谷歌云 防火墙 比较特殊。。
