### ISSUE TITLE
[错误]  SSL 证书测试签发和生成失败

### ISSUE THREAD

**Issue by weiladeng** [wulabing/V2Ray_ws-tls_bash_onekey#149]
error:Fetching http://www.2020ms.tk/.well-known/acme-challenge/iLmgB857LyGASIwCs5ZaVLXabOC_OaAlSEPTuMdh9vw: Error getting validation data

error:Fetching http://www.2020ms.tk/.well-known/acme-challenge/K7NHZOpuCcknkAcHq0cPMuE3RVpr2KLYbbRBn6to220: Error getting validation data

**Comment by xiaolilir** [comment]
同遇到

**Comment by weiladeng** [comment]
> 同遇到
不知道怎么解决。太郁闷了。

**Comment by wulabing** [comment]
更换其他的NS 服务商
