### ISSUE TITLE
如何使用本脚本通过 cloudflare 拯救被墙的 IP

### ISSUE THREAD

**Issue by nemo2018** [wulabing/V2Ray_ws-tls_bash_onekey#15]
近期，由于众所周知的原因，那个又那个了。我的谷歌云服务器4个都是瘫痪状态，没死，就是瘫着。我在推里面也看到不止一个人有这个反应。
这时候想重提一下cf嵌套的事情，能否把你这个case #11 里面提到的3点具体如何实现说一下。特殊时候用的上。
谢谢！🙏

**Comment by wulabing** [comment]
好 我会在稍后贴出详细的修改方法

**Comment by nemo2018** [comment]
非常非常非常非常的感谢！

**Comment by wulabing** [comment]
相关内容已编辑完成 请查阅 [Wiki ](https://github.com/wulabing/V2Ray_ws-tls_bash_onekey/wiki/%E5%A6%82%E4%BD%95%E6%9B%B4%E6%94%B9%E9%85%8D%E7%BD%AE%E4%BD%BF%E8%AF%A5%E8%84%9A%E6%9C%AC%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8-cloudflare-%E5%B5%8C%E5%A5%97)

**Comment by nemo2018** [comment]
改nginx没问题。我说下我的cf配置。

1 我查了一下cf自动检测如果对方是websocket自动开启，不需要额外配置。
2 主要是crypto页面，

- SSL - Flexible

- Always use HTTPS - On

- HSTS
Status: On
Max-Age: 1 month
Include subdomains: On
Preload: On
No-sniff: On
(这部分不是很懂就都启动了）
其他都保留默认。

重启了nginx，过了一会重启客户端好像不工作，客户端log一直是 connection refused.
我觉得还是cf里面哪个没配置对。

**Comment by wulabing** [comment]
SSL 需要改成强制

**Comment by wulabing** [comment]
我的想法是所有的SSL部分都交给 cloudflare 证书也交给它

**Comment by nemo2018** [comment]
![cf](https://user-images.githubusercontent.com/37334053/37556559-f96d8252-2a32-11e8-9eb1-1a930a25c3f8.jpeg)
这是cf关于ssl配置的解释，我的理解服务器如果只开80给cf，不能用强制了，只能用flexible，不知道我的理解对不对。
关于HSTS确实没概念。

**Comment by nemo2018** [comment]
HTTPS (SSL) must be enabled in order to use HSTS.

If you turn on HSTS and do not have HTTPS for your website, browsers will not accept the HSTS setting.
If you have HSTS enabled and leave Cloudflare, you need to continue to support HTTPS through a new service provider otherwise your site will become inaccessible to visitors until you support HTTPS again.
If you turn off Cloudflare’s HTTPS while HSTS is enabled, and you don’t have a valid SSL certificate on your origin server, your website will become inaccessible to visitors.

好像，我们的做法HSTS也不需要吧？服务器没开启ssl

**Comment by wulabing** [comment]
HSTS 和 ALways use https的功能是一样的，不会影响什么大局。

**Comment by wulabing** [comment]
我的理解服务器如果只开80给cf，不能用强制了，只能用flexible，不知道我的理解对不对。
不对，服务器只开80的目的是为了不和 cloudflare的https发生冲突。所以要改成 full 把整个https部分交给它

**Comment by wulabing** [comment]
其实cloudflare提供了非常全的功能，并且能够自适应，我改的东西比较多，实际上有很多种不同的修改方法，可以用不同的nginx配置去适应

**Comment by nemo2018** [comment]
对。我的感觉完全不改变v2ray的设置，cf配置合适了应该可以无缝切换，可以简单的切换cf里面cdn enable/disable而不去改变服务器任何配置包括v2ray 和nginx
这是我的感觉而已。还没找到合适路子。

**Comment by nemo2018** [comment]
调通了。
还是用你wiki里面修改后的nginx配置。
ssl用flexible
always use ssl 关闭
其他都默认，是通的。
此时用域名看不管80还是443，都是可爱的计算器。
谢谢哈！

**Comment by nemo2018** [comment]
简单说，Crypto那夜都保持默认。
从昨天到今天都用的这个方法。
然后发现，iOS下小火箭跑vmess很慢，换了Kitsunebi速度恢复预期。
谢谢！

**Comment by nemo2018** [comment]
@wulabing 看到wiki里面更改的内容和第一版不同了。我测试了一下，**按照当前的方法更改nginx配置的话，CF里面的SSL要放到full或者full(strict)上。在flexible上是不work的。**
你再测试一下。
然后测试了一下开和关CDN，发现服务器，客户端都无需做任何动作，等一会就生效了。非常好。这样非常时期加CDN，正常情况下关闭CDN。灵活性高，操作简便。
你要是有时间再测试测试，我的办法比较笨，用DNS工具check一下域名的IP是自己的还是CF的。然后浏览器访问域名看看证书是CF的还是Let's Encrpt的。还要多试试看看有没有其他问题。

**Comment by wulabing** [comment]
先采纳结果，我这暂时没有多余的域名可以调过去进行测试。可以等等其他的V2友们尝试一下

## 本 issue 等待更多反馈结果

**Comment by nemo2018** [comment]
完全赞同。
issue应该改一个更响亮的标题：如果挽救被ban的小鸡

**Comment by nemo2018** [comment]
中午得空在我那个1月份就被ban得死死的搬瓦工上测试了一下。
ubuntu16.04. 脚本+wiki修改配置。客户端是ios Kitsunebi。连续放了一个多小时视频，中间偶尔卡二下，主要是赶上下班时间了，公司网络会慢一点。其他的感觉良好，完全符合预期。安装，修改配置一气呵成。
建议CF的ALWAYS USE HTTPS 这次给他on了。因为服务器不监听80了，如果直接敲域名访问页面无返回，而是要敲HTTPS域名。把那个ON了就是直接敲域名也自己转去HTTPS。完美。
另外我发觉ios，我们这个脚本使用的配置条件下，小火箭好慢，Kitsunebi正常。不知道其他朋友有没有体会？
![image](https://user-images.githubusercontent.com/37334053/37637518-39c0a110-2c43-11e8-9418-e0197a5ca8cf.png)

**Comment by nemo2018** [comment]
实测nginx配置里面的监听80那部分不去掉也是没问题的。就让他听反正什么也听不到。
所以就更简单了，只要一句话，打开CF 的SSL 到full或者full(strick)

**Comment by speeedturtle** [comment]
我的小鸡也被墙了，谁能帮忙做中转

**Comment by nemo2018** [comment]
谁也帮不了你，只能靠自己。

**Comment by fbens** [comment]
> 
> 
> 改nginx没问题。我说下我的cf配置。
> 
> 1 我查了一下cf自动检测如果对方是websocket自动开启，不需要额外配置。
> 2 主要是crypto页面，
> 
>     * SSL - Flexible
> 
>     * Always use HTTPS - On
> 
>     * HSTS
>       Status: On
>       Max-Age: 1 month
>       Include subdomains: On
>       Preload: On
>       No-sniff: On
>       (这部分不是很懂就都启动了）
>       其他都保留默认。
> 
> 
> 重启了nginx，过了一会重启客户端好像不工作，客户端log一直是 connection refused.
> 我觉得还是cf里面哪个没配置对。

非常疑惑，我在cf加了一个域名，bwg.mysite.com 指向被墙的IP，new.mysite指向国外未墙的IP。
两个都将cf的那个证书key cert放到他们443的里面去，访问 new.mysite.com HTTPS 马上生效，但被墙的那个怎么都无法访问，提示错误 525 错误。
