### ISSUE TITLE
nginx太大了。改成caddy吧。自动签发SSL

### ISSUE THREAD

**Issue by jsyzjhj** [wulabing/V2Ray_ws-tls_bash_onekey#153]
nginx太大了。改成caddy吧。自动签发SSL！

**Comment by wulabing** [comment]
233 脚本中 已经使用了caddy 可以转用233的脚本

cb8848 <notifications@github.com> 于2020年1月10日周五 上午10:10写道：

**Comment by jackytang** [comment]
Nginx reload一下行不行呢，这样就不会断了
