### ISSUE TITLE
因套用CDN后出现安装问题，是否按提示继续？

### ISSUE THREAD

**Issue by tlsalex** [wulabing/V2Ray_ws-tls_bash_onekey#154]
域名用cloudflare来解析，套用了CDN,安装脚本解析到的地址与本地实际公网地址不一致，导致如下错误：
域名dns解析IP：104.xx.xx.8
本机IP: 1xx.xx.xx.1xx
[错误]  请确保域名添加了正确的 A 记录，否则将无法正常使用 V2ray
[错误]  域名dns解析IP 与 本机IP 不匹配 是否继续安装？（y/n）

是否按提示继续？

**Comment by tlsalex** [comment]
我直接在hosts 文件里添加了我域名和IP的解析后就好了

**Comment by Whale-fall** [comment]
> 我直接在hosts 文件里添加了我域名和IP的解析后就好了
具体是怎么进行操作的呢？
