### ISSUE TITLE
v2ray 安装失败，提示手动安装，但手动安装提示已经安装了最新版，咋搞

### ISSUE THREAD

**Issue by tlsalex** [wulabing/V2Ray_ws-tls_bash_onekey#155]
Extracting V2Ray package to /tmp/v2ray.
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /tmp/v2ray/config.json
   creating: /tmp/v2ray/doc/
  inflating: /tmp/v2ray/doc/readme.md
  inflating: /tmp/v2ray/geoip.dat
  inflating: /tmp/v2ray/geosite.dat
   creating: /tmp/v2ray/systemd/
  inflating: /tmp/v2ray/systemd/v2ray.service
   creating: /tmp/v2ray/systemv/
  inflating: /tmp/v2ray/systemv/v2ray
  inflating: /tmp/v2ray/v2ctl
 extracting: /tmp/v2ray/v2ctl.sig
  inflating: /tmp/v2ray/v2ray
 extracting: /tmp/v2ray/v2ray.sig
  inflating: /tmp/v2ray/vpoint_socks_vmess.json
  inflating: /tmp/v2ray/vpoint_vmess_freedom.json
PORT:19555
UUID:4f2bd067-b639-4bf3-af88-5baeb0da4c2e
Updating software repo
Installing daemon
Error: Nothing to do
Failed to install daemon. Please install it manually.
[错误]  安装 V2ray 失败
[root@2020 src]# bash <(curl -L -s https://install.direct/go.sh)
Latest version v4.22.1 is already installed.

**Comment by tlsalex** [comment]
强制卸载v2ray后，错误消失

**Comment by jiz4oh** [comment]
原因：
这个是 v2ray 官方脚本 go.sh 的下的 installInitScript 函数判断错误，当系统为 CentOS7 时且已存在 v2ray.service 时会尝试安装 daemon，但是并没有这个软件，所以报错。

解决方式：

1. 可以手动删除 /etc/systemd/system/v2ray.service 文件：
    rm /etc/systemd/system/v2ray.service
然后输入 y 回车
重新运行脚本

1. 手动修改 go.sh 第332行 与 install.sh 第270行的两个判断函数

1. 等待 v2ray 官方修复

**Comment by zry118** [comment]
> 原因：
> 这个是 v2ray 官方脚本 go.sh 的下的 installInitScript 函数判断错误，当系统为 CentOS7 时且已存在 v2ray.service 时会尝试安装 daemon，但是并没有这个软件，所以报错。
> 
> 解决方式：
> 
> 1. 可以手动删除 /etc/systemd/system/v2ray.service 文件：
>    rm /etc/systemd/system/v2ray.service
>    然后输入 y 回车
>    重新运行脚本
> 2. 手动修改 go.sh 第332行 与 install.sh 第270行的两个判断函数
> 3. 等待 v2ray 官方修复

感谢大神
