### ISSUE TITLE
感谢作者，刚刚开始学习网络知识不久，关于一键脚本有一些建议和问题需要请教

### ISSUE THREAD

**Issue by kerryfangda** [wulabing/V2Ray_ws-tls_bash_onekey#158]
建议：onekey优化脚本似乎有锐速内核但是没有加速模块，导致部署后访问YTB速度很慢，我在安装脚本后自行安装了BBR，问题解决，建议加入脚本内

问题：我目前绑定域名正确解析VPS的IP后可以正常扶墙，但在软路由内将Switch游戏机设置为全局代理后，Switch的游戏下载和更新正常加速，但游戏却无法联机，应该是由于TLS伪装HTTPS流量后，TCP可以正常连接，但基于UDP的游戏封包不能正常传输，我在客户端json内的inbound内写了udp=true也不可以，请问这个是否有解决办法？

感谢你的付出！

**Comment by wulabing** [comment]
这个问题需要询问v2ray上游
