### ISSUE TITLE
[错误]  编译检查 失败

### ISSUE THREAD

**Issue by yefeiyu** [wulabing/V2Ray_ws-tls_bash_onekey#159]
How should I do?
CentOS

```
[OK]  即将开始编译安装 Nginx, 过程稍久，请耐心等待 
checking for OS
 + Linux 4.18.0-80.11.2.el8_0.x86_64 x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 8.3.1 20190507 (Red Hat 8.3.1-4) (GCC) 
checking for gcc -pipe switch ... found
.........
checking for PCRE library ... not found
checking for PCRE library in /usr/local/ ... not found
checking for PCRE library in /usr/include/pcre/ ... not found
checking for PCRE library in /usr/pkg/ ... not found
checking for PCRE library in /opt/local/ ... not found

./configure: error: the HTTP rewrite module requires the PCRE library.
You can either disable the module by using --without-http_rewrite_module
option, or install the PCRE library into the system, or build the PCRE library
statically from the source with nginx by using --with-pcre=<path> option.

[错误]  编译检查 失败
```

**Comment by yefeiyu** [comment]
再次安装时提示：
```

CentOS-8.0 - AppStream                                                                                           149  B/s |  38  B     00:00    
Error: Failed to synchronize cache for repo 'AppStream'
[错误]  安装 chrony 时间同步服务  失败
```

**Comment by yefeiyu** [comment]
请输入数字：1
[OK]  当前用户是root用户，进入安装流程 
[OK]  当前系统为 Centos 8 Core 
Failed to set locale, defaulting to C
CentOS-8.0 - AppStream                                                                                            80  B/s |  38  B     00:00    
Error: Failed to synchronize cache for repo 'AppStream'
[OK]  firewalld 已关闭 
Failed to stop ufw.service: Unit ufw.service not loaded.
[OK]  ufw 已关闭 
Failed to set locale, defaulting to C
CentOS-8.0 - AppStream                                                                                           165  B/s |  38  B     00:00    
Error: Failed to synchronize cache for repo 'AppStream'
[错误]  安装 chrony 时间同步服务  失败

**Comment by wulabing** [comment]
暂时对C8的适配不是特别完全，可以尝试使用C7
