### ISSUE TITLE
请问一个域名2个vps怎么搞

### ISSUE THREAD

**Issue by pjomvndy** [wulabing/V2Ray_ws-tls_bash_onekey#16]
想一个域名绑定2个vps的ip。因为用此脚本，2个vps的v2rya配置文件不一样，是不是需要自己手动修改成一样的呢？

**Comment by wulabing** [comment]
:）没有想过这个问题，按道理来说修改成一致的以后应该可以用。需要修改nginx配置文件中 location的path  和V2ray配置文件中的 UUID

**Comment by nemo2018** [comment]
简单。用cf。
我就是这样的，一个域名，前面加子域名，4个vps

**Comment by nemo2018** [comment]
不用CF也行，就在域名管理里面随便加。

**Comment by pjomvndy** [comment]
@wulabing   试过了，不行，这样弄的话，单个账号都不能用了，好象是一个域名绑定两个ip无法正常使用。

**Comment by pjomvndy** [comment]
@nemo2018   你的方法是把一个域名分成子域名，然后变成了多个config.json，客户端分开使用，对吧？如果想一个客户端就能调用这个域名的所有vps服务器，怎么做？

**Comment by nemo2018** [comment]
@pjomvndy 对。
本质上你这个需求和vps提供服务无关，完全是怎么设置dns的问题。
你有多个vps，多个ip地址对不对？
加A记录就行了。一条A记录一个ip。
负载均衡又是另一个问题。
