### ISSUE TITLE
新版安装后不断的出现502 Bad Gateway > websocket: bad handshake]

### ISSUE THREAD

**Issue by lmhdrive** [wulabing/V2Ray_ws-tls_bash_onekey#161]
大佬，非常感谢您提供的脚本，安装时非常顺利，也比较人性化，但安装后运行不了，不断的出现这个提示，请方便给分析一下。
2020/02/02 22:57:11 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://lmhdrive.ml/8fb6a2f2/): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by Lemooonade** [comment]
问题同上

**Comment by LinYKen** [comment]
同问，我的是301：Moved Permanently
