### ISSUE TITLE
[错误] SSL 证书测试签发失败

### ISSUE THREAD

**Issue by Jacky-op-sm** [wulabing/V2Ray_ws-tls_bash_onekey#164]
尝试过了新建二级域名，但是没有什么用处
![1](https://user-images.githubusercontent.com/52201411/73724399-359ded00-4766-11ea-92f6-3b1a63f5b158.PNG)
![2](https://user-images.githubusercontent.com/52201411/73724401-36cf1a00-4766-11ea-92c0-553d66fe945f.PNG)
求帮助，被这个困扰了好久

**Comment by wulabing** [comment]
结果显示 nameserver 可能存在故障，需要变更域名的 NS 服务

**Comment by Catherine-88** [comment]
换一个DNS解析服务商试一下，我就是这样解决的
