### ISSUE TITLE
[错误]  SSL 证书测试签发失败

### ISSUE THREAD

**Issue by tlsalex** [wulabing/V2Ray_ws-tls_bash_onekey#166]
[Wed Feb  5 11:26:20 CST 2020] www.xxxxx.info:Verify error:Fetching http://www.xxxxx.info/.well-known/acme-challenge/Xzw_kgA6KdOzr2ssXPrITRFre4fgo4Px7CRZerZTHM4: Error getting validation data
[Wed Feb  5 11:26:20 CST 2020] Please add '--debug' or '--log' to check more details.
[Wed Feb  5 11:26:20 CST 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[错误]  SSL 证书测试签发失败

上一个版本似乎没这个问题，如何能使用上一版的脚本

**Comment by Catherine-88** [comment]
换一个DNS解析服务商试一下，我就是这样解决的

**Comment by rosefun** [comment]
```
Mon Feb 17 13:53:54 CST 2020] Standalone mode.
[Mon Feb 17 13:53:54 CST 2020] LISTEN     0      128         :::80                      :::*                   users:(("caddy",pid=20495,fd=3))
[Mon Feb 17 13:53:54 CST 2020] tcp port 80 is already used by 80                      
[Mon Feb 17 13:53:54 CST 2020] Please stop it first
[Mon Feb 17 13:53:54 CST 2020] _on_before_issue.
[错误]  SSL 证书测试签发失败 

```
这个问题呢？

**Comment by weishimi** [comment]
+1 试过多次，域名解析明明是对的

**Comment by wulabing** [comment]
最近的版本并没有对证书更新部分进行过代码变更
请更换NS服务商

**Comment by vantaa** [comment]
在ubuntu上遇到同样问题，发现是防火墙/iptables的缘故，修改iptables的规则就好了。
（PS.  一键安装脚本在这里做的事情是，用socat假装一个监听80端口的http服务器，所以nginx此时没有启动是正常的。）

**Comment by ethansunqing** [comment]
> 在ubuntu上遇到同样问题，发现是防火墙/iptables的缘故，修改iptables的规则就好了。
> （PS. 一键安装脚本在这里做的事情是，用socat假装一个监听80端口的http服务器，所以nginx此时没有启动是正常的。）
怎么修改规则，就没有开启防火墙也不行？我也换了cloudfire 都没有用。郁闷中

**Comment by ethansunqing** [comment]
> > > 在ubuntu上遇到同样问题，发现是防火墙/iptables的缘故，修改iptables的规则就好了。
> > > （PS. 一键安装脚本在这里做的事情是，用socat假装一个监听80端口的http服务器，所以nginx此时没有启动是正常的。）
> > > 怎么修改规则，就没有开启防火墙也不行？我也换了cloudfire 都没有用。郁闷中
> 
> 你可以试试关闭防火墙，不过，如果是ubuntu，你要记得检查firewalld和iptables两个服务都关闭了

都关了 脚本一开始也都有关闭操作；还是不行 不知道哪里出问题  加--debug或者--log log文件在哪里看？

**Comment by vantaa** [comment]
> > > > 在ubuntu上遇到同样问题，发现是防火墙/iptables的缘故，修改iptables的规则就好了。
> > > > （PS. 一键安装脚本在这里做的事情是，用socat假装一个监听80端口的http服务器，所以nginx此时没有启动是正常的。）
> > > > 怎么修改规则，就没有开启防火墙也不行？我也换了cloudfire 都没有用。郁闷中
> > 
> > 
> > 你可以试试关闭防火墙，不过，如果是ubuntu，你要记得检查firewalld和iptables两个服务都关闭了
> 
> 都关了 脚本一开始也都有关闭操作；还是不行 不知道哪里出问题 加--debug或者--log log文件在哪里看？

1.  还有你的vps管理/配置页面也可能有防火墙规则，你也要检查那边。 

2.  --debug/--log是acme.sh的option

`acme() {
    if "$HOME"/.acme.sh/acme.sh --issue -d "${domain}" --standalone -k ec-256 --force --test; then
        echo -e "${OK} ${GreenBG} SSL 证书测试签发成功，开始正式签发 ${Font}"
        rm -rf "$HOME/.acme.sh/${domain}_ecc"
        sleep 2
    else
        echo -e "${Error} ${RedBG} SSL 证书测试签发失败 ${Font}"
        rm -rf "$HOME/.acme.sh/${domain}_ecc"
        exit 1
    fi`

**Comment by hangyejiadao** [comment]
> 换一个DNS解析服务商试一下，我就是这样解决的

@Catherine-88  请问怎么换

**Comment by ZFQQ2** [comment]
我的也这样一键v2报错"SSL证书测试签发失败" 
VPS端，无防火墙，Cloudflare 端的防火墙安全级别设置为关。我连 SSL/TLS 加密模式也设为 关闭（不安全）。
求救，我是头一次接触LINUX。谢谢，能详解。
racoonbbj@gmail.com

**Comment by vantaa** [comment]
执行
`"$HOME"/.acme.sh/acme.sh --issue -d google.com --standalone -k ec-256 --force --test --debug`
会有详细的出错信息

**Comment by kuangxiaoye** [comment]
root@ecs-4ebe:~# "$HOME"/.acme.sh/acme.sh --issue -d www.rickandmorty.tool --standalone -k ec-256 --force --test --debug
[Tue Nov 17 21:50:16 CST 2020] Lets find script dir.
[Tue Nov 17 21:50:16 CST 2020] _SCRIPT_='/root/.acme.sh/acme.sh'
[Tue Nov 17 21:50:16 CST 2020] _script='/root/.acme.sh/acme.sh'
[Tue Nov 17 21:50:16 CST 2020] _script_home='/root/.acme.sh'
[Tue Nov 17 21:50:16 CST 2020] Using default home:/root/.acme.sh
[Tue Nov 17 21:50:16 CST 2020] Using config home:/root/.acme.sh
https://github.com/acmesh-official/acme.sh
v2.8.8
[Tue Nov 17 21:50:16 CST 2020] Running cmd: issue
[Tue Nov 17 21:50:16 CST 2020] _main_domain='www.rickandmorty.tool'
[Tue Nov 17 21:50:16 CST 2020] _alt_domains='no'
[Tue Nov 17 21:50:16 CST 2020] Using config home:/root/.acme.sh
[Tue Nov 17 21:50:16 CST 2020] Using ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Tue Nov 17 21:50:16 CST 2020] ACME_DIRECTORY='https://acme-staging-v02.api.letsencrypt.org/directory'
[Tue Nov 17 21:50:16 CST 2020] DOMAIN_PATH='/root/.acme.sh/www.rickandmorty.tool_ecc'
[Tue Nov 17 21:50:16 CST 2020] Using ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Tue Nov 17 21:50:16 CST 2020] _init api for server: https://acme-staging-v02.api.letsencrypt.org/directory
[Tue Nov 17 21:50:16 CST 2020] GET
[Tue Nov 17 21:50:16 CST 2020] url='https://acme-staging-v02.api.letsencrypt.org/directory'
[Tue Nov 17 21:50:16 CST 2020] timeout=
[Tue Nov 17 21:50:16 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue Nov 17 21:50:17 CST 2020] ret='0'
[Tue Nov 17 21:50:17 CST 2020] ACME_KEY_CHANGE='https://acme-staging-v02.api.letsencrypt.org/acme/key-change'
[Tue Nov 17 21:50:17 CST 2020] ACME_NEW_AUTHZ
[Tue Nov 17 21:50:17 CST 2020] ACME_NEW_ORDER='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Tue Nov 17 21:50:17 CST 2020] ACME_NEW_ACCOUNT='https://acme-staging-v02.api.letsencrypt.org/acme/new-acct'
[Tue Nov 17 21:50:17 CST 2020] ACME_REVOKE_CERT='https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert'
[Tue Nov 17 21:50:17 CST 2020] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Tue Nov 17 21:50:17 CST 2020] ACME_NEW_NONCE='https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Nov 17 21:50:17 CST 2020] ACME_VERSION='2'
[Tue Nov 17 21:50:17 CST 2020] Using CA: https://acme-staging-v02.api.letsencrypt.org/directory
[Tue Nov 17 21:50:17 CST 2020] _on_before_issue
[Tue Nov 17 21:50:17 CST 2020] _chk_main_domain='www.rickandmorty.tool'
[Tue Nov 17 21:50:17 CST 2020] _chk_alt_domains
[Tue Nov 17 21:50:17 CST 2020] Le_LocalAddress
[Tue Nov 17 21:50:17 CST 2020] d='www.rickandmorty.tool'
[Tue Nov 17 21:50:17 CST 2020] Check for domain='www.rickandmorty.tool'
[Tue Nov 17 21:50:17 CST 2020] _currentRoot='no'
[Tue Nov 17 21:50:17 CST 2020] Standalone mode.
[Tue Nov 17 21:50:17 CST 2020] _checkport='80'
[Tue Nov 17 21:50:17 CST 2020] _checkaddr
[Tue Nov 17 21:50:17 CST 2020] Using: ss
[Tue Nov 17 21:50:17 CST 2020] d
[Tue Nov 17 21:50:17 CST 2020] _saved_account_key_hash is not changed, skip register account.
[Tue Nov 17 21:50:17 CST 2020] Read key length:
[Tue Nov 17 21:50:17 CST 2020] Creating domain key
[Tue Nov 17 21:50:17 CST 2020] Using config home:/root/.acme.sh
[Tue Nov 17 21:50:17 CST 2020] ACME_DIRECTORY='https://acme-staging-v02.api.letsencrypt.org/directory'
[Tue Nov 17 21:50:17 CST 2020] Use length 256
[Tue Nov 17 21:50:17 CST 2020] Using ec name: prime256v1
[Tue Nov 17 21:50:17 CST 2020] The domain key is here: /root/.acme.sh/www.rickandmorty.tool_ecc/www.rickandmorty.tool.key
[Tue Nov 17 21:50:17 CST 2020] _createcsr
[Tue Nov 17 21:50:17 CST 2020] Single domain='www.rickandmorty.tool'
[Tue Nov 17 21:50:17 CST 2020] Getting domain auth token for each domain
[Tue Nov 17 21:50:17 CST 2020] d
[Tue Nov 17 21:50:17 CST 2020] url='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Tue Nov 17 21:50:17 CST 2020] payload='{"identifiers": [{"type":"dns","value":"www.rickandmorty.tool"}]}'
[Tue Nov 17 21:50:17 CST 2020] RSA key
[Tue Nov 17 21:50:17 CST 2020] HEAD
[Tue Nov 17 21:50:17 CST 2020] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Nov 17 21:50:17 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -I  '
[Tue Nov 17 21:50:18 CST 2020] _ret='0'
[Tue Nov 17 21:50:18 CST 2020] POST
[Tue Nov 17 21:50:18 CST 2020] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Tue Nov 17 21:50:18 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue Nov 17 21:50:19 CST 2020] _ret='0'
[Tue Nov 17 21:50:19 CST 2020] code='400'
[Tue Nov 17 21:50:19 CST 2020] Le_LinkOrder
[Tue Nov 17 21:50:19 CST 2020] Le_OrderFinalize
[Tue Nov 17 21:50:19 CST 2020] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rejectedIdentifier",
  "detail": "Error creating new order :: Cannot issue for \"www.rickandmorty.tool\": Domain name does not end with a valid public suffix (TLD)",
  "status": 400
}
[Tue Nov 17 21:50:19 CST 2020] pid
[Tue Nov 17 21:50:19 CST 2020] No need to restore nginx, skip.
[Tue Nov 17 21:50:19 CST 2020] _clearupdns
[Tue Nov 17 21:50:19 CST 2020] dns_entries
[Tue Nov 17 21:50:19 CST 2020] skip dns.
[Tue Nov 17 21:50:19 CST 2020] _on_issue_err
[Tue Nov 17 21:50:19 CST 2020] Please add '--debug' or '--log' to check more details.
[Tue Nov 17 21:50:19 CST 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Tue Nov 17 21:50:19 CST 2020] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.0l  10 Sep 2019
apache:
apache doesn't exist.
nginx:
nginx doesn't exist.
socat:
socat by Gerhard Rieger - see www.dest-unreach.org
socat version 1.7.3.1 on Jul 14 2017 13:52:03
   running on Linux version #1 SMP Debian 4.9.210-1 (2020-01-20), release 4.9.0-12-amd64, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #undef WITH_READLINE
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #define WITH_LIBWRAP 1
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/


> 执行
> `"$HOME"/.acme.sh/acme.sh --issue -d google.com --standalone -k ec-256 --force --test --debug`
> 会有详细的出错信息。
> 一般如果是防火墙问题，这一步基本可以确定问题。
> 
> 如果自己还解决不了，建议把上面命令中 google.com 替换成你自己的真实域名，再把完整输出贴上来帮助分析。提醒：贴上来的内容请给你的真实域名打马赛克，避免不必要的麻烦。

**Comment by vantaa** [comment]
> root@ecs-4ebe:~# "$HOME"/.acme.sh/acme.sh --issue -d [www.111andmorty.tool](http://www.111andmorty.tool) --standalone -k ec-256 --force --test --debug
...
...
> [Tue Nov 17 21:50:18 CST 2020] POST
> [Tue Nov 17 21:50:18 CST 2020] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
> [Tue Nov 17 21:50:18 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header -g '
> [Tue Nov 17 21:50:19 CST 2020] _ret='0'
> [Tue Nov 17 21:50:19 CST 2020] code='400'
> [Tue Nov 17 21:50:19 CST 2020] Le_LinkOrder
> [Tue Nov 17 21:50:19 CST 2020] Le_OrderFinalize
> [Tue Nov 17 21:50:19 CST 2020] Create new order error. Le_OrderFinalize not found. {
> "type": "urn:ietf:params:acme:error:rejectedIdentifier",
> "detail": "Error creating new order :: Cannot issue for "www.111andmorty.tool": Domain name does not end with a valid public suffix (TLD)",
> "status": 400
...

Domain name does not end with a valid public suffix (TLD) ?  你的域名是.tool结尾的？

**Comment by vantaa** [comment]
> `[Tue Oct 12 13:13:33 EDT 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60 [Tue Oct 12 13:13:33 EDT 2021] ret='60' [Tue Oct 12 13:13:33 EDT 2021] _hcode='60' [Tue Oct 12 13:13:35 EDT 2021] Can not init api for: https://acme-staging-v02.api.letsencrypt.org/directory. [Tue Oct 12 13:13:35 EDT 2021] Sleep 10 and retry.`
> 
> 我遇到了这样的问题

```
[Tue Oct 12 13:13:33 EDT 2021] GET 
[Tue Oct 12 13:13:33 EDT 2021] url='https://acme-staging-v02.api.letsencrypt.org/directory' 
[Tue Oct 12 13:13:33 EDT 2021] timeout= 
[Tue Oct 12 13:13:33 EDT 2021] displayError='0' 
[Tue Oct 12 13:13:33 EDT 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header -L -g ' 
[Tue Oct 12 13:13:33 EDT 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60 
[Tue Oct 12 13:13:33 EDT 2021] ret='60' 
```
hmmm...   
如果你手动执行 `curl https://acme-staging-v02.api.letsencrypt.org/directory` 命令的话输出是什么？

**Comment by daleyzou** [comment]
> > `[Tue Oct 12 13:13:33 EDT 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60 [Tue Oct 12 13:13:33 EDT 2021] ret='60' [Tue Oct 12 13:13:33 EDT 2021] _hcode='60' [Tue Oct 12 13:13:35 EDT 2021] Can not init api for: https://acme-staging-v02.api.letsencrypt.org/directory. [Tue Oct 12 13:13:35 EDT 2021] Sleep 10 and retry.`
> > 我遇到了这样的问题
> 
> ```
> [Tue Oct 12 13:13:33 EDT 2021] GET 
> [Tue Oct 12 13:13:33 EDT 2021] url='https://acme-staging-v02.api.letsencrypt.org/directory' 
> [Tue Oct 12 13:13:33 EDT 2021] timeout= 
> [Tue Oct 12 13:13:33 EDT 2021] displayError='0' 
> [Tue Oct 12 13:13:33 EDT 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header -L -g ' 
> [Tue Oct 12 13:13:33 EDT 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60 
> [Tue Oct 12 13:13:33 EDT 2021] ret='60' 
> ```
> 
> hmmm... 那个链接的页面说60是服务器的SSL证书无效 (???) 如果你手动执行 `curl https://acme-staging-v02.api.letsencrypt.org/directory` 命令的话输出是什么？

恩，现在也还有点迷糊， 查找后按照 https://github.com/acmesh-official/acme.sh/issues/3729#issue-1014134486 的， 把 acme.sh 拉去服务器修改了，执行本地的改动脚本就可以了
