### ISSUE TITLE
怎么使用自己的证书？

### ISSUE THREAD

**Issue by wjk199511140034** [wulabing/V2Ray_ws-tls_bash_onekey#168]
由于ns不给力还有其他种种原因，遇到多次证书签发失败，最后导致超过限制，看到脚本里好像已经有判断本地证书的语句了，但是打上了#号
acme.sh这个脚本也是很迷，看了一下官方说明居然没看太懂。。

**Comment by wjk199511140034** [comment]
仔细读了下代码。改下install_v2ray_ws_tls()就好了
只要把
`install_v2ray_ws_tls(){
    .....
    #ssl_judge_and_install
    .....
    #acme_cron_update
}`
证书丢到根目录data里面，如果是pem格式的还需要改一下/etc/nginx/conf/conf.d/v2ray.conf里面的ssl_certificate项，改完了别忘了重启下nginx
申请了个TrustAsia的一年证书，把cron里面的计划删掉了，凑合着用吧
acme：我太难了

**Comment by updater1234** [comment]
README.md里面不就已经有了如何使用自己证书的方法了吗？
