### ISSUE TITLE
Nginx无法启动

### ISSUE THREAD

**Issue by ALESONICFICTIOZ** [wulabing/V2Ray_ws-tls_bash_onekey#17]
作者您好！我刚刚新开的机器，在执行脚本前未安装任何软件。域名已确认解析到VPS上，然后用V2Ray_ws-tls_bash_onekey一键脚本安装，SSL证书可以正常获取，安装中间一切正常，但在结束安装时会提示： job for nginx.service failed because the control process exited with error code. see "systemctl status nginx.service" and "journalctl -xe" for details.。  网站无法访问。

**Comment by ALESONICFICTIOZ** [comment]
在以往的版本从未遇到过此类问题，我使用这个脚本大概有一个多月的时间，每次的更新我都安装过，同一台VPS，每次安装前都会Reinstall。只有这次出现了job for nginx.service failed because the control process exited with error code. see "systemctl status nginx.service" and "journalctl -xe" for details.

**Comment by wulabing** [comment]
感谢您的反馈，昨天进行了一次小幅度的更新，因此并没有对脚本的可用性进行测试
## 目前进行紧急修复

**Comment by ALESONICFICTIOZ** [comment]
这可能是目前最优秀的V2ray安装脚本，感谢作者，加油！！

**Comment by wulabing** [comment]
感谢您的支持。

**Comment by ALESONICFICTIOZ** [comment]
作者你好！上次出现的这个问题今天安装时候又出现了，看来是脚本新版本的问题？^_^   Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
