### ISSUE TITLE
用乌班图18.04 一键安装使后没有任何错误不能使用

### ISSUE THREAD

**Issue by Havynlam** [wulabing/V2Ray_ws-tls_bash_onekey#172]
[OK]  Nginx 启动 完成 
[OK]  V2ray 启动 完成 
[OK]  设置 v2ray 开机自启 完成 
Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service → /etc/systemd/system/nginx.service.
[OK]  设置 Nginx 开机自启 完成 
--2020-02-12 13:25:16--  https://raw.githubusercontent.com/wulabing/V2Ray_ws-tls_bash_onekey/dev/ssl_update.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.13
3, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 259 [text/plain]
Saving to: ‘/usr/bin/ssl_update.sh’
ssl_update.sh                100%[============================================>]     259  --.-KB/s    in 0s      
2020-02-12 13:25:17 (10.2 MB/s) - ‘/usr/bin/ssl_update.sh’ saved [259/259]
[OK]  cron 计划任务更新 完成 

求助大神~~服务器是谷歌的，能Ping 通。。

**Comment by wulabing** [comment]
请使用脚本中的tls选项调整tls至兼容版本
