### ISSUE TITLE
最后一步 设置nginx开机自启失败

### ISSUE THREAD

**Issue by authon** [wulabing/V2Ray_ws-tls_bash_onekey#174]
请问如何手动加入自启呢？

systemctl enable nginx.service 
Synchronizing state of nginx.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable nginx
Failed to execute operation: File exists

使用上面这条命令还是失败

**Comment by wulabing** [comment]
file exists 说明nginx已经设置成功自启了，不会有什么影响，可以无视

**Comment by authon** [comment]
> file exists 说明nginx已经设置成功自启了，不会有什么影响，可以无视

好的嘞
