### ISSUE TITLE
个人建议现阶段对最后生成的TLS模式选择后再生成配置信息

### ISSUE THREAD

**Issue by solidworkstechnology** [wulabing/V2Ray_ws-tls_bash_onekey#177]
个人建议现阶段对最后生成的TLS模式选择后再生成配置信息
不然整个流程有点乱的感觉

**Comment by wulabing** [comment]
tls版本选择会在下个版本会加入到安装流程中

solidworkstechnology <notifications@github.com> 于2020年2月14日周五 下午2:41写道：
