### ISSUE TITLE
vps重启之后不能自动运行nginx和v2ray服务

### ISSUE THREAD

**Issue by laoz77** [wulabing/V2Ray_ws-tls_bash_onekey#18]
我在搬瓦工的openvz服务器上用您这个脚本安装了v2ray，各方面都工作挺好，但是碰到了一个问题：
服务器重启之后需要手动启动这两个服务。请问如何使机器重启后自动运行这两个服务？

**Comment by wulabing** [comment]
可以执行以下命令进行尝试
```
systemctl enable v2ray

systemctl enable nginx

```

**Comment by laoz77** [comment]
@wulabing  感谢，更改试过了。重启后可以自动启动了。
