### ISSUE TITLE
脚本的已安装判断根据是什么？

### ISSUE THREAD

**Issue by jiangfengringo** [wulabing/V2Ray_ws-tls_bash_onekey#183]
我用一键脚本安装了http2的，但因为之前已经有了LNMP，所以冲突原网站不可显示，后来使用脚本卸载，但完成后再运行依旧显示已安装h2版本，想问一下脚本判断本机是否安装V2ray的依据是什么？

**Comment by wulabing** [comment]
通过判断导出vmess前的json文件是否存在来判断，这是一个bug，将会修复

**Comment by wulabing** [comment]
这一部分逻辑也发生变化
