### ISSUE TITLE
为什么我的墙外机器安装了之后墙内还是无法访问呢？

### ISSUE THREAD

**Issue by joostshao** [wulabing/V2Ray_ws-tls_bash_onekey#188]
wget -N --no-check-certificate -q -O install.sh "https://raw.githubusercontent.com/wulabing/V2Ray_ws-tls_bash_onekey/master/install.sh" && chmod +x install.sh && bash install.sh

有人知道吗？ 好奇了我，我用的cloudfare的解析，也点了灰色的，难道是xyz域名的问题？求助

请输入数字：10
[OK]  V2ray+ws+tls 安装成功
 V2ray 配置信息
 地址（address）: xxx.xyz
 端口（port）： 443
 用户id（UUID）： f68fb99c-4a9d-4913-94a4-894c871cea61
 额外id（alterId）： 2
 加密方式（security）： 自适应
 传输协议（network）： ws
 伪装类型（type）： none
 路径（不要落下/）： /d98a0a48/
 底层传输安全： tls

**Comment by joostshao** [comment]
被墙过的就不能生效了吗？

**Comment by kevinriver** [comment]
我安装完之后伪装的网站能访问，v2rayNG里也能连上，但点测试就返回失败：context deadline exceeded(Client.Timeout exceeded while awaiting headers)或者返回 status != 204: 400 Bad Request

**Comment by joostshao** [comment]
和楼上的一样，超时了，难道就只是为了预防？

**Comment by kevinriver** [comment]
楼主，你的可以用了吗？怎么解决

**Comment by joostshao** [comment]
cloudfare的云朵最后还是要点成黄色，点亮
