### ISSUE TITLE
pc端可用，但在手机上如iphone 11无法连接

### ISSUE THREAD

**Issue by xiaopengzhu** [wulabing/V2Ray_ws-tls_bash_onekey#2]
kitsunebi 扫码另一个一键脚本安装的v2ray可用，这个脚本的无法使用，在电脑上是可以使用的，提示无法提供安全的连接，下截数据0kb

**Comment by orxvan** [comment]
同

**Comment by erres** [comment]
iphone 8P  IOS14  ****kitsunebi 扫码另一个一键脚本安装的v2ray可用，这个脚本的无法使用，在电脑上是可以使用的，提示无法提供安全的连接，下截数据0kb

**Comment by tinet-jutt** [comment]
同

**Comment by huohu4399** [comment]
同 mac可以  ios不能用   路由器也不能用  为什么

**Comment by ShiiraRuruin** [comment]
这个有办法解决吗

**Comment by Huaweidev** [comment]
> 这个有办法解决吗

手机上手工修改传输方式为h2，及启动“允许不安全”就行，我同样问题按这样已经解决了。

**Comment by marxhehe** [comment]
> iphone 8P IOS14 ****kitsunebi 扫码另一个一键脚本安装的v2ray可用，这个脚本的无法使用，在电脑上是可以使用的，提示无法提供安全的连接，下截数据0kb

所以是哪个脚本？
