### ISSUE TITLE
部分vps缺少crontab

### ISSUE THREAD

**Issue by ylx2016** [wulabing/V2Ray_ws-tls_bash_onekey#2]
部分vps缺少crontab

**Comment by wulabing** [comment]
了解，我会在今日晚些时候进行完善，感谢反馈

2018年1月27日 上午8:45，"dr" <notifications@github.com>写道：

**Comment by ylx2016** [comment]
你匹配80端口，是模糊匹配的
unix  5      [ ]         DGRAM                    11580    /run/systemd/journal/socket
unix  3      [ ]         STREAM     CONNECTED     15080
像这种怎么解..

**Comment by wulabing** [comment]
关于 crontab 的问题，已经进行了部分完善，
关于端口匹配问题，如果您有更好的检测方案，欢迎您 pull requests，

**Comment by ylx2016** [comment]
改成这个试试
`lsof -i:"$1" | wc -l`

**Comment by ylx2016** [comment]
pull requests 不会玩

**Comment by wulabing** [comment]
曾经比较过lsof -i 和 netstat 的区别。查过一些资料也没发现，
现经测试lsof -i 显示的信息确实更完善确
## 本条建议已采纳
