### ISSUE TITLE
centos 下 http 强制跳转 https

### ISSUE THREAD

**Issue by dylanbai8** [wulabing/V2Ray_ws-tls_bash_onekey#20]
昨天紧跟你的步伐更新了一下脚本
奇怪 centos 下 http 跳转不起作用，最终还是没搞明白

**Comment by wulabing** [comment]
的确2.0之后的脚本我没再在centos上测试过，下午晚些时候我会开一台机器测试一下

**Comment by wulabing** [comment]
我找了一台机器做了一下测试，我的这个脚本是可以正常跳转的  安装的nginx版本是1.12.2  需要你那面的更多反馈，包括配置信息，nginx版本，或者直接贴出网站

**Comment by dylanbai8** [comment]
好的，谢谢，我再研究一下看看。
