### ISSUE TITLE
使用脚本后，原有网站无法正常访问

### ISSUE THREAD

**Issue by hxlive** [wulabing/V2Ray_ws-tls_bash_onekey#203]
我的小服务器上有私人自用的小网站，几个朋友共享信息的，之前的部署的有SSR，后来改用了v2ray，部署倒是很顺利，不过却导致之前的小网站无法正常使用，特来求助一下~

**Comment by gwhao** [comment]
nginx代理的就是你之前网站的80，443端口，你可以通过nginx配置，或者将脚本所给的网站目录里的内容改成你的小网站的内容。我问一下，我脚本搭建完之后v2rayN就是连不上。你的是刚搭建的吗？用的什么系统？debian，Ubuntu？

**Comment by hxlive** [comment]
谢谢，我一会儿去试试看，我是刚搭建的，主机系统是CentOS7

**Comment by cchhuuaann1** [comment]
![Screenshot_2020-03-18-10-33-18-645_com github android](https://user-images.githubusercontent.com/26471985/77430092-99af6a00-6e15-11ea-8ace-87d6b359571c.jpg)

麻烦你自己看看脚本源码先 哪怕不认识代码 中文注释你应该看的懂吧

**Comment by hxlive** [comment]
自己解决了
