### ISSUE TITLE
能否添加同时部署v2ray_ws_tls和trojan两种代理方式的脚本

### ISSUE THREAD

**Issue by easyinplay** [wulabing/V2Ray_ws-tls_bash_onekey#204]
非常感谢wulabing朋友的辛苦工作，使用过很多脚本还是觉得这里的最好用，感觉很多地方都透露着作者的用心。希望可以集成一下trojan，可以同时部署 v2ray ws-tls 和 trojan（防止某一天突然因为不可抗力其中的一张方式不能用了） ，虽然也能找到其他部署trojan的脚步但是找不到可以同时部署的，因为都占用443端口，如果安装两个脚本会提示安装失败，希望朋友能够出一个集成的一键脚本可以同时部署这两种方式

**Comment by cchhuuaann1** [comment]
trojan和Nginx反代的v2ray是一个道理 都是“反代” 如果哪一天这个脚本凉凉了 那么就意味着trojan也凉了

**Comment by jinwyp** [comment]
https://github.com/jinwyp/one_click_script 可以同时的
