### ISSUE TITLE
更新&安装 失败

### ISSUE THREAD

**Issue by Miauyo** [wulabing/V2Ray_ws-tls_bash_onekey#215]
Installing V2Ray vhttps://api.github.com/repos/v2ray/v2ray-core/releases/22545481 on x86_64
Downloading V2Ray: https://github.com/v2ray/v2ray-core/releases/download/vhttps://api.github.com/repos/v2ray/v2ray-core/releases/22545481/v2ray-linux-64.zip                                                                          
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     30      0 --:--:-- --:--:-- --:--:--    30
awk: not an option: -e
[/tmp/v2ray/v2ray.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/v2ray/v2ray.zip or
        /tmp/v2ray/v2ray.zip.zip, and cannot find /tmp/v2ray/v2ray.zip.ZIP, period.
Archive:  /tmp/v2ray/v2ray.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/v2ray/v2ray.zip or
        /tmp/v2ray/v2ray.zip.zip, and cannot find /tmp/v2ray/v2ray.zip.ZIP, period.
Failed to copy V2Ray binary and resources.
[错误]  安装 V2ray 失败

**Comment by Miauyo** [comment]
好吧是go.sh这个脚本的问题

**Comment by hxy493045049** [comment]
这个问题怎么处理呀...
