### ISSUE TITLE
Nginx 下载完成后Openssl下载错误

### ISSUE THREAD

**Issue by kuaichongdian** [wulabing/V2Ray_ws-tls_bash_onekey#225]
小白一个 换过系统试了好几次 端口也是默认的（也试过别的），域名是freenom的
一直卡在这个步骤  :<
我自己把openssl-1.1.1d.tar.gz下载了（PC上） 但是不知道怎么用 网上也没找到相关的教程
——————————————————————————————————————————
[OK]  Nginx 下载 完成
--2020-04-01 11:23:13--  https://www.openssl.org/source/openssl-1.1.1d.tar.gz
Resolving www.openssl.org (www.openssl.org)... 104.92.164.40, 2600:1406:3:582::c1e, 2600:1406:3:583::c1e
Connecting to www.openssl.org (www.openssl.org)|104.92.164.40|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-01 11:23:14 ERROR 404: Not Found.

[错误]  openssl 下载 失败

**Comment by kuaichongdian** [comment]
好吧 我用的是新开的机子 可能是域名没完全解析完成？（不懂）
过了几个小时再弄就没这问题了
遇到同样问题的小伙伴可以等一段时间 再执行脚本

**Comment by afishwithdream** [comment]
我也是404，按理说没解析到不应该是404啊

**Comment by afishwithdream** [comment]
手动wget也还是404   QAQ

**Comment by afishwithdream** [comment]
果然reboot解决一切问题。。。
