### ISSUE TITLE
 http2 及 tls1.3 适配

### ISSUE THREAD

**Issue by windy1lee** [wulabing/V2Ray_ws-tls_bash_onekey#23]
能否快速上线，还有能否加入客户端配置文件生成功能，方便直接导入

**Comment by windy1lee** [comment]
openssl升级脚本：
1
2
3
4
5
6
7
8
9
10
11
12
13
14
#!/bin/sh
cd /opt/download
wget https://www.openssl.org/source/openssl-1.0.2k.tar.gz
tar -zxvf openssl-1.0.2k.tar.gz
cd openssl-1.0.2k
./config --prefix=/usr/local/openssl 
make && make install 
mv /usr/bin/openssl   /usr/bin/openssl.OFF 
mv /usr/include/openssl   /usr/include/openssl.OFF 
ln -s   /usr/local/openssl/bin/openssl   /usr/bin/openssl 
ln -s   /usr/local/openssl/include/openssl   /usr/include/openssl 
echo "/usr/local/openssl/lib"  >>/etc/ld.so.conf 
ldconfig -v
openssl version -a


这个升级的命令应该是可以的啊，我刚刚把我打得升级了！1

**Comment by wulabing** [comment]
目前的计划是等待 openssl 1.1.1的稳定版发布之后 再对 openssl 部分通过本脚本进行处理
Centos 的 openssl 升级部分还没做测试，

**Comment by wulabing** [comment]
而且就算你升级了openssl 通过源安装的nginx 还是用的老版本openssl 这一点可以通过 nginx -V 来看到，想要解决这个问题，根本方法就是通过编译安装nginx
debian9的默认openssl版本符合http2的要求，安装就可以正常实现
TLS1.3 目前只能靠编译安装
