### ISSUE TITLE
如何添加cdn

### ISSUE THREAD

**Issue by Angel0726** [wulabing/V2Ray_ws-tls_bash_onekey#235]
注册了cloudfare。打开cdn之后，v2ray就不能用了
![image](https://user-images.githubusercontent.com/32816780/79589234-ac147f00-8107-11ea-8bdc-2662a451ecbf.png)

**Comment by seozed** [comment]
https://github.com/wulabing/V2Ray_ws-tls_bash_onekey/wiki/%E5%A6%82%E4%BD%95%E6%9B%B4%E6%94%B9%E9%85%8D%E7%BD%AE%E4%BD%BF%E8%AF%A5%E8%84%9A%E6%9C%AC%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8-cloudflare-%E5%B5%8C%E5%A5%97
