### ISSUE TITLE
关于ip限速

### ISSUE THREAD

**Issue by pjomvndy** [wulabing/V2Ray_ws-tls_bash_onekey#25]
我搭建的v2ray账号想分享给朋友使用，但考虑到流量问题，想对连接v2ray服务器的ip进行限速，比如单个ip限速300kb/s，请问能做到吗？

**Comment by wulabing** [comment]
V2ray-core目前好像没有提供相关的限速功能，所以说暂时无法通过V2ray做到，可以尝试一些其他的方式

**Comment by pjomvndy** [comment]
我对linux不熟悉，请问你可以帮忙提供一些方法吗？

**Comment by wulabing** [comment]
关于限速这项操作，相比较而言还是建议使用相对成熟的 shadowsocksr 
如果一定需要用V2ray的话，貌似可以通过 iptables 来完成，应该也有其他的方式，不过操作相对而言比较复杂，不建议不熟悉linux的用户尝试

**Comment by 0080004** [comment]
@wulabing 一键脚本怎么升级呢，目前是V3.1

**Comment by pjomvndy** [comment]
谢谢 @wulabing
