### ISSUE TITLE
关于v2ray流控的讨论

### ISSUE THREAD

**Issue by dylanbai8** [wulabing/V2Ray_ws-tls_bash_onekey#26]
是否可以通过nginx来实现v2ray的流控呢。参考文献：http://blog.51cto.com/dragondragon/1692339

**Comment by wulabing** [comment]
有时间我会去看看

dylanbai8 <notifications@github.com> 于 2018年4月7日周六 19:53写道：

**Comment by dylanbai8** [comment]
简单测试了一下，好像是可以的。

**Comment by dylanbai8** [comment]
我个人暂时没有这样的需求，只是恰好想到这里了而已，顺道讨论一下。既然nginx的下载速度是可控的，那么多个server配合多端口或者多个二级域名就可以实现v2ray多账号的流控。甚至可以实现一个小型的机场，或者方便大家共享v2ray账号。
