### ISSUE TITLE
[错误]  证书应用 失败

### ISSUE THREAD

**Issue by wehuss** [wulabing/V2Ray_ws-tls_bash_onekey#27]
[Sun Apr 24 15:46:34 CST 2022] Installing key to: /data/v2ray.key
touch: cannot touch '/data/v2ray.key': No such file or directory
[错误]  证书应用 失败

**Comment by pizzamx** [comment]
> [Sun Apr 24 15:46:34 CST 2022] Installing key to: /data/v2ray.key touch: cannot touch '/data/v2ray.key': No such file or directory [错误] 证书应用 失败

碰到了，建一个目录 mkdir /data
