### ISSUE TITLE
安装后v2ray服务启动失败

### ISSUE THREAD

**Issue by wmh90** [wulabing/V2Ray_ws-tls_bash_onekey#277]
一键安装后，客户端无法连接服务端，元素周期表打开正常。
再次运行脚本，显示 当前已安装版本:None

`root@ubuntu:~# sudo systemctl status v2ray
* v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: en
   Active: failed (Result: exit-code) since Sat 2020-08-29 14:49:35 CST; 3min 14
  Process: 1839 ExecStart=/usr/local/bin/v2ray -config /etc/v2ray/config.json (c
 Main PID: 1839 (code=exited, status=23)

Aug 29 14:49:35 ubuntu systemd[1]: v2ray.service: Main process exited, code=exit
Aug 29 14:49:35 ubuntu systemd[1]: v2ray.service: Failed with result 'exit-code'
Aug 29 14:49:35 ubuntu systemd[1]: v2ray.service: Service hold-off time over, sc
Aug 29 14:49:35 ubuntu systemd[1]: v2ray.service: Scheduled restart job, restart
Aug 29 14:49:35 ubuntu systemd[1]: Stopped V2Ray Service.
Aug 29 14:49:35 ubuntu systemd[1]: v2ray.service: Start request repeated too qui
Aug 29 14:49:35 ubuntu systemd[1]: v2ray.service: Failed with result 'exit-code'
Aug 29 14:49:35 ubuntu systemd[1]: Failed to start V2Ray Service.
`

`root@ubuntu:~# journalctl -u v2ray
-- Logs begin at Sat 2020-08-29 13:47:12 CST, end at Sat 2020-08-29 14:52:59 CST
Aug 29 14:03:10 ubuntu systemd[1]: Started V2Ray Service.
Aug 29 14:03:10 ubuntu v2ray[28663]: V2Ray 4.27.4 (V2Fly, a community-driven edi
Aug 29 14:03:10 ubuntu v2ray[28663]: A unified platform for anti-censorship.
Aug 29 14:03:10 ubuntu v2ray[28663]: main: failed to create server > v2ray.com/c
Aug 29 14:03:10 ubuntu systemd[1]: v2ray.service: Main process exited, code=exit
Aug 29 14:03:10 ubuntu systemd[1]: v2ray.service: Failed with result 'exit-code'
`

`-- Logs begin at Sat 2020-08-29 13:47:12 CST, end at Sat 2020-08-29 14:52:59 CST. --
Aug 29 14:03:10 ubuntu systemd[1]: Started V2Ray Service.
Aug 29 14:03:10 ubuntu v2ray[28663]: V2Ray 4.27.4 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.7 linux/amd64)
Aug 29 14:03:10 ubuntu v2ray[28663]: A unified platform for anti-censorship.
Aug 29 14:03:10 ubuntu v2ray[28663]: main: failed to create server > v2ray.com/core/app/log: failed to initialize access logger > open /var/log/v2ray/access.log: permission denied
Aug 29 14:03:10 ubuntu systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
`

**Comment by Fegor** [comment]
昨天也遇到同样的问题。
反复换了个几个IP也是。最后晚上wulabing更新后，再次部署，可以了。

**Comment by jinwyp** [comment]
推荐一个脚本 支持 trojan-go trojan v2ray 共存，升级和卸载,自动证书续签.可以修改root和ssh端口 支持WS+CDN https://github.com/jinwyp/one_click_script

**Comment by NavlysChen** [comment]
我现在还是这样的问题，请问楼主解决了吗？

**Comment by neighbads** [comment]
ExecStart=/usr/local/bin/v2ray -config /etc/v2ray/config.json 这个路径别换。用默认目录的就没问题了

@NavlysChen

**Comment by NavlysChen** [comment]
> ExecStart = / usr / local / bin / v2ray -config /etc/v2ray/config.json这个路径别换。用替换目录的就没问题了
> 
> @NavlysChen

主要是我啥都没换

**Comment by wmh90** [comment]
问题已修复

**Comment by jwli6-shuwen** [comment]
请问楼主解决了吗？

**Comment by crazymartin** [comment]
同样的问题，只能重装么？
