### ISSUE TITLE
使用http2 over tls脚本没有安装nginx

### ISSUE THREAD

**Issue by laoz77** [wulabing/V2Ray_ws-tls_bash_onekey#28]
您好，我在全新debian 8 x64系统上使用Vmess + HTTP2 over TLS 脚本，执行之后发现没有安装nginx。在v2rayN中导入配置json文件也无法翻墙。

root@vultr:~# systemctl status  v2ray
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled)
   Active: active (running) since Wed 2018-04-11 06:10:52 UTC; 41s ago
 Main PID: 447 (v2ray)
   CGroup: /system.slice/v2ray.service
           └─447 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Apr 11 06:10:52 vultr.guest systemd[1]: Starting V2Ray Service...
Apr 11 06:10:52 vultr.guest systemd[1]: Started V2Ray Service.
Apr 11 06:10:52 vultr.guest v2ray[447]: V2Ray v3.16 (die Commanderin) 20180405
Apr 11 06:10:52 vultr.guest v2ray[447]: A unified platform for anti-censorship.
Apr 11 06:10:52 vultr.guest v2ray[447]: 2018/04/11 06:10:52 [Warning] Core: V2Ray v3.16 started
root@vultr:~# systemctl status nginx
● nginx.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
root@vultr:~#

**Comment by wulabing** [comment]
因为这是昨天才发布第一版的测试版脚本，确实有可能出现一些问题（虽然我简单的进行了测试）。我会稍后在db8上重新尝试安装，请等待返回结果

**Comment by laoz77** [comment]
感谢！需要我上传log吗？

**Comment by wulabing** [comment]
我这在全新的db8下测试是正常的，我想您可能需要升级一下客户端的core版本，客户端core 在3.14版本以上才支持http2

**Comment by laoz77** [comment]
您好，我已经把客户端更换成了3.16版本。但是还是无法正常工作。
我把运行v2rayN的部分日志贴在这里，供您参考。

配置成功 
Custom-import custom@4/11/2018
启动服务(4/11/2018 2:51:03 PM)......
V2Ray v3.16 (die Commanderin) 20180405
A unified platform for anti-censorship.
2018/04/11 14:51:03 [Warning] Core: V2Ray v3.16 started
2018/04/11 14:51:03 [Info] [4184144720] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 14:51:03 [Info] [2252886195] Proxy|Socks: TCP Connect request to tcp:www.twitter.com:443
2018/04/11 14:51:03 [Info] Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2018/04/11 14:51:03 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 14:51:03 tcp:127.0.0.1:57657 accepted tcp:www.google.com:443 
2018/04/11 14:51:03 tcp:127.0.0.1:57662 accepted tcp:www.twitter.com:443 
2018/04/11 14:51:03 tcp:127.0.0.1:57659 accepted tcp:www.google.com:443 
2018/04/11 14:51:03 [Info] [3486005411] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 14:51:03 [Info] App|Dispatcher: default route for udp:8.8.8.8:53
2018/04/11 14:51:03 [Info] App|Proxyman|Mux: dispatching request to udp:8.8.8.8:53
2018/04/11 14:51:03 tcp:127.0.0.1:57660 accepted tcp:www.google.com:443 
2018/04/11 14:51:03 [Info] App|Router: looking for IP for domain: www.twitter.com
2018/04/11 14:51:03 [Info] [2619452948] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 14:51:03 tcp:127.0.0.1:57663 accepted tcp:venus-1.web.telegram.org:443 
2018/04/11 14:51:03 [Info] [1934481200] Proxy|Socks: TCP Connect request to tcp:venus-1.web.telegram.org:443
2018/04/11 14:51:03 tcp:127.0.0.1:57661 accepted tcp:www.google.com:443 
2018/04/11 14:51:03 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 14:51:03 [Info] [2701831686] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 14:51:03 tcp:127.0.0.1:57664 accepted tcp:pluto.web.telegram.org:443 
2018/04/11 14:51:03 tcp:127.0.0.1:57658 accepted tcp:capi.grammarly.com:443 
2018/04/11 14:51:03 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 14:51:03 [Info] [1798904830] Proxy|Socks: TCP Connect request to tcp:pluto.web.telegram.org:443
2018/04/11 14:51:03 [Info] [2337540705] Proxy|Socks: TCP Connect request to tcp:capi.grammarly.com:443
2018/04/11 14:51:03 [Info] App|Router: looking for IP for domain: venus-1.web.telegram.org
2018/04/11 14:51:03 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 14:51:03 [Info] App|Router: looking for IP for domain: pluto.web.telegram.org
2018/04/11 14:51:03 [Info] App|Router: looking for IP for domain: capi.grammarly.com
2018/04/11 14:51:07 [Info] Transport|Internet|UDP: failed to handle UDP input > context canceled
2018/04/11 14:51:07 [Info] App|Proxyman|Mux: failed to fetch all input > context canceled
2018/04/11 14:51:08 tcp:127.0.0.1:57668 rejected  Proxy|Socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:57668: i/o timeout
2018/04/11 14:51:08 tcp:127.0.0.1:57665 rejected  Proxy|Socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:57665: i/o timeout
2018/04/11 14:51:08 [Info] [1087172801] App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:57668: i/o timeout
2018/04/11 14:51:08 [Info] [762589210] App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:57665: i/o timeout
2018/04/11 14:51:08 tcp:127.0.0.1:57667 rejected  Proxy|Socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:57667: i/o timeout
2018/04/11 14:51:08 [Info] [4248527944] App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:57667: i/o timeout
2018/04/11 14:51:08 tcp:127.0.0.1:57669 rejected  Proxy|Socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:57669: i/o timeout
2018/04/11 14:51:08 [Info] [2325774985] App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:57669: i/o timeout
2018/04/11 14:51:08 tcp:127.0.0.1:57666 rejected  Proxy|Socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:57666: i/o timeout
2018/04/11 14:51:08 [Info] [1158211220] App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:57666: i/o timeout
2018/04/11 14:51:08 [Info] [2037106949] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 14:51:08 tcp:127.0.0.1:57679 accepted tcp:www.google.com:443 
2018/04/11 14:51:08 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 14:51:08 [Info] Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2018/04/11 14:51:08 [Info] App|Dispatcher: default route for udp:8.8.8.8:53
2018/04/11 14:51:08 [Info] App|Proxyman|Mux: dispatching request to udp:8.8.8.8:53
2018/04/11 14:51:09 tcp:127.0.0.1:57686 accepted tcp:www.google.com:443 
2018/04/11 14:51:09 [Info] [1111522621] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 14:51:09 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 14:51:11 [Info] [1181406927] Proxy|Socks: TCP Connect request to tcp:www.facebook.com:443
2018/04/11 14:51:11 tcp:127.0.0.1:57689 accepted tcp:www.facebook.com:443 
2018/04/11 14:51:11 [Info] App|Router: looking for IP for domain: www.facebook.com
2018/04/11 14:51:11 [Info] Transport|Internet|UDP: establishing new connection for udp:8.8.4.4:53
2018/04/11 14:51:11 [Info] App|Dispatcher: default route for udp:8.8.4.4:53
2018/04/11 14:51:11 [Info] App|Proxyman|Mux: dispatching request to udp:8.8.4.4:53
2018/04/11 14:51:12 [Info] Transport|Internet|UDP: failed to handle UDP input > EOF
2018/04/11 14:51:13 [Info] Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2018/04/11 14:51:13 [Info] App|Dispatcher: default route for udp:8.8.8.8:53
2018/04/11 14:51:13 [Info] App|Proxyman|Mux: dispatching request to udp:8.8.8.8:53
2018/04/11 14:51:15 [Info] Transport|Internet|UDP: failed to handle UDP input > EOF
2018/04/11 14:51:15 [Info] App|Proxyman|Mux: failed to fetch all input > context canceled
2018/04/11 14:51:16 [Info] Transport|Internet|UDP: establishing new connection for udp:8.8.4.4:53
2018/04/11 14:51:16 [Info] App|Dispatcher: default route for udp:8.8.4.4:53
2018/04/11 14:51:16 [Info] App|Proxyman|Mux: dispatching request to udp:8.8.4.4:53
2018/04/11 14:51:17 [Info] Transport|Internet|UDP: failed to handle UDP input > EOF
2018/04/11 14:51:17 [Info] App|Proxyman|Mux: failed to fetch all input > context canceled
2018/04/11 14:51:18 tcp:127.0.0.1:57709 accepted tcp:venus-1.web.telegram.org:443 
2018/04/11 14:51:18 [Info] [35306349] Proxy|Socks: TCP Connect request to tcp:venus-1.web.telegram.org:443
2018/04/11 14:51:18 [Info] App|Router: looking for IP for domain: venus-1.web.telegram.org
2018/04/11 14:51:18 [Info] Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2018/04/11 14:51:18 [Info] App|Dispatcher: default route for udp:8.8.8.8:53
2018/04/11 14:51:18 [Info] App|Proxyman|Mux: dispatching request to udp:8.8.8.8:53

**Comment by wulabing** [comment]
尝试修改客户端配置文件中以下字段
```
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
```
为
```
  "dns": {
    "servers": [
      "localhost"
    ]
  },
```

并进行测试

**Comment by laoz77** [comment]
仍然不行，log如下：

配置成功 
Custom-import custom@4/11/2018
启动服务(4/11/2018 3:43:27 PM)......
V2Ray v3.16 (die Commanderin) 20180405
A unified platform for anti-censorship.
2018/04/11 15:43:27 [Warning] Core: V2Ray v3.16 started
2018/04/11 15:43:37 [Info] [3354129049] Proxy|Socks: TCP Connect request to tcp:notifications.google.com:443
2018/04/11 15:43:37 [Info] [2045262601] Proxy|Socks: TCP Connect request to tcp:apis.google.com:443
2018/04/11 15:43:37 [Info] [3498306877] Proxy|Socks: TCP Connect request to tcp:play.google.com:443
2018/04/11 15:43:37 tcp:127.0.0.1:62653 accepted tcp:notifications.google.com:443 
2018/04/11 15:43:37 tcp:127.0.0.1:62652 accepted tcp:apis.google.com:443 
2018/04/11 15:43:37 tcp:127.0.0.1:62654 accepted tcp:play.google.com:443 
2018/04/11 15:43:37 [Info] App|Router: looking for IP for domain: apis.google.com
2018/04/11 15:43:37 [Info] App|Router: looking for IP for domain: play.google.com
2018/04/11 15:43:37 [Info] App|Router: looking for IP for domain: notifications.google.com
2018/04/11 15:43:37 [Info] [3354129049] App|Dispatcher: default route for tcp:notifications.google.com:443
2018/04/11 15:43:37 [Info] [3354129049] App|Proxyman|Mux: dispatching request to tcp:notifications.google.com:443
2018/04/11 15:43:37 [Info] [2045262601] App|Dispatcher: default route for tcp:apis.google.com:443
2018/04/11 15:43:37 [Info] [2045262601] App|Proxyman|Mux: dispatching request to tcp:apis.google.com:443
2018/04/11 15:43:37 [Info] [3498306877] App|Dispatcher: default route for tcp:play.google.com:443
2018/04/11 15:43:37 [Info] [3498306877] App|Proxyman|Mux: dispatching request to tcp:play.google.com:443
2018/04/11 15:43:38 [Info] [765688350] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 15:43:38 tcp:127.0.0.1:62656 accepted tcp:www.google.com:443 
2018/04/11 15:43:38 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 15:43:38 [Info] [765688350] App|Dispatcher: default route for tcp:www.google.com:443
2018/04/11 15:43:38 [Info] [765688350] App|Proxyman|Mux: dispatching request to tcp:www.google.com:443
2018/04/11 15:43:38 [Info] [2377756959] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 15:43:38 tcp:127.0.0.1:62657 accepted tcp:www.google.com:443 
2018/04/11 15:43:38 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 15:43:38 [Info] [2377756959] App|Dispatcher: default route for tcp:www.google.com:443
2018/04/11 15:43:38 [Info] [2377756959] App|Proxyman|Mux: dispatching request to tcp:www.google.com:443
2018/04/11 15:43:38 [Info] [2854932899] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 15:43:38 tcp:127.0.0.1:62658 accepted tcp:www.google.com:443 
2018/04/11 15:43:38 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 15:43:38 [Info] [2854932899] App|Dispatcher: default route for tcp:www.google.com:443
2018/04/11 15:43:38 [Info] [2854932899] App|Proxyman|Mux: dispatching request to tcp:www.google.com:443
2018/04/11 15:43:39 [Info] [1133002257] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 15:43:39 tcp:127.0.0.1:62660 accepted tcp:www.google.com:443 
2018/04/11 15:43:39 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 15:43:39 [Info] [1133002257] App|Dispatcher: default route for tcp:www.google.com:443
2018/04/11 15:43:39 [Info] [1133002257] App|Proxyman|Mux: dispatching request to tcp:www.google.com:443
2018/04/11 15:43:39 [Info] [4101301040] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 15:43:39 tcp:127.0.0.1:62661 accepted tcp:www.google.com:443 
2018/04/11 15:43:39 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 15:43:39 [Info] [4101301040] App|Dispatcher: default route for tcp:www.google.com:443
2018/04/11 15:43:39 [Info] [4101301040] App|Proxyman|Mux: dispatching request to tcp:www.google.com:443
2018/04/11 15:43:40 [Info] [1692184541] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 15:43:40 tcp:127.0.0.1:62663 accepted tcp:www.google.com:443 
2018/04/11 15:43:40 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 15:43:40 [Info] [1692184541] App|Dispatcher: default route for tcp:www.google.com:443
2018/04/11 15:43:40 [Info] [1692184541] App|Proxyman|Mux: dispatching request to tcp:www.google.com:443
2018/04/11 15:43:41 tcp:127.0.0.1:62666 accepted tcp:clients5.google.com:443 
2018/04/11 15:43:41 tcp:127.0.0.1:62667 accepted tcp:lh3.googleusercontent.com:443 
2018/04/11 15:43:41 [Info] [2314379972] Proxy|Socks: TCP Connect request to tcp:clients5.google.com:443
2018/04/11 15:43:41 [Info] [558419385] Proxy|Socks: TCP Connect request to tcp:lh3.googleusercontent.com:443
2018/04/11 15:43:41 [Info] [1351805634] Proxy|Socks: TCP Connect request to tcp:ogs.google.com:443
2018/04/11 15:43:41 tcp:127.0.0.1:62668 accepted tcp:ogs.google.com:443 
2018/04/11 15:43:41 tcp:127.0.0.1:62670 accepted tcp:www.gstatic.com:443 
2018/04/11 15:43:41 tcp:127.0.0.1:62669 accepted tcp:ssl.gstatic.com:443 
2018/04/11 15:43:41 [Info] App|Router: looking for IP for domain: clients5.google.com
2018/04/11 15:43:41 [Info] [3374385227] Proxy|Socks: TCP Connect request to tcp:www.gstatic.com:443
2018/04/11 15:43:41 [Info] App|Router: looking for IP for domain: lh3.googleusercontent.com
2018/04/11 15:43:41 [Info] [1942504855] Proxy|Socks: TCP Connect request to tcp:ssl.gstatic.com:443
2018/04/11 15:43:41 [Info] App|Router: looking for IP for domain: ogs.google.com
2018/04/11 15:43:41 [Info] App|Router: looking for IP for domain: ssl.gstatic.com
2018/04/11 15:43:41 [Info] App|Router: looking for IP for domain: www.gstatic.com
2018/04/11 15:43:41 [Info] [2314379972] App|Dispatcher: default route for tcp:clients5.google.com:443
2018/04/11 15:43:41 [Info] [2314379972] App|Proxyman|Mux: dispatching request to tcp:clients5.google.com:443
2018/04/11 15:43:41 [Info] [1351805634] App|Dispatcher: default route for tcp:ogs.google.com:443
2018/04/11 15:43:41 [Info] [1351805634] App|Proxyman|Mux: dispatching request to tcp:ogs.google.com:443
2018/04/11 15:43:41 [Info] [558419385] App|Dispatcher: default route for tcp:lh3.googleusercontent.com:443
2018/04/11 15:43:41 [Info] [558419385] App|Proxyman|Mux: dispatching request to tcp:lh3.googleusercontent.com:443
2018/04/11 15:43:41 [Info] [1942504855] App|Dispatcher: taking detour [direct] for [tcp:ssl.gstatic.com:443]
2018/04/11 15:43:41 [Info] [1942504855] Proxy|Freedom: opening connection to tcp:ssl.gstatic.com:443
2018/04/11 15:43:41 [Info] [1942504855] Transport|Internet|TCP: dialing TCP to tcp:ssl.gstatic.com:443
2018/04/11 15:43:41 [Info] [3374385227] App|Dispatcher: taking detour [direct] for [tcp:www.gstatic.com:443]
2018/04/11 15:43:41 [Info] [3374385227] Proxy|Freedom: opening connection to tcp:www.gstatic.com:443
2018/04/11 15:43:41 [Info] [3374385227] Transport|Internet|TCP: dialing TCP to tcp:www.gstatic.com:443
2018/04/11 15:43:52 [Info] [3747774854] Proxy|Socks: TCP Connect request to tcp:beacons.gcp.gvt2.com:443
2018/04/11 15:43:52 tcp:127.0.0.1:62679 accepted tcp:beacons.gcp.gvt2.com:443 
2018/04/11 15:43:52 [Info] App|Router: looking for IP for domain: beacons.gcp.gvt2.com
2018/04/11 15:43:52 [Info] [3747774854] App|Dispatcher: default route for tcp:beacons.gcp.gvt2.com:443
2018/04/11 15:43:52 [Info] [3747774854] App|Proxyman|Mux: dispatching request to tcp:beacons.gcp.gvt2.com:443
2018/04/11 15:44:08 [Info] [2624997573] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 15:44:08 tcp:127.0.0.1:62689 accepted tcp:www.google.com:443 
2018/04/11 15:44:08 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 15:44:08 [Info] [2624997573] App|Dispatcher: default route for tcp:www.google.com:443
2018/04/11 15:44:08 [Info] [2624997573] App|Proxyman|Mux: dispatching request to tcp:www.google.com:443
2018/04/11 15:44:08 [Info] [507566954] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 15:44:08 tcp:127.0.0.1:62690 accepted tcp:www.google.com:443 
2018/04/11 15:44:08 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 15:44:08 [Info] [507566954] App|Dispatcher: default route for tcp:www.google.com:443
2018/04/11 15:44:08 [Info] [507566954] App|Proxyman|Mux: dispatching request to tcp:www.google.com:443
2018/04/11 15:44:14 [Info] [2594991128] Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2018/04/11 15:44:14 tcp:127.0.0.1:62695 accepted tcp:www.google.com:443 
2018/04/11 15:44:14 [Info] App|Router: looking for IP for domain: www.google.com
2018/04/11 15:44:14 [Info] [2594991128] App|Dispatcher: default route for tcp:www.google.com:443
2018/04/11 15:44:14 [Info] [2594991128] App|Proxyman|Mux: dispatching request to tcp:www.google.com:443

**Comment by laoz77** [comment]
补充一下：采用您基于path的那个脚本安装的一直都可以用。

**Comment by wulabing** [comment]
等我晚间回去的时候再看看哈

**Comment by wulabing** [comment]
可以将你的client配置信息和服务端的config信息贴上来嘛（可以对serveraddress做一下处理）

**Comment by laoz77** [comment]
好，晚一点发。我现在在外边。

**Comment by wulabing** [comment]
没看出什么问题，core这两天比较频繁的更新，你现在可以尝试重新安装之后手动向新版的V2RAYNG添加配置，看看这样是否可行

**Comment by laoz77** [comment]
好的，谢谢您的帮助！
