### ISSUE TITLE
有没有人谷歌学术没法用的?

### ISSUE THREAD

**Issue by Li6lac** [wulabing/V2Ray_ws-tls_bash_onekey#287]
必须换ip解决吗？

**Comment by Shouyupedia** [comment]
谷歌学术ban了你的VPS的ipv4，在服务器的host里面加上谷歌学术的ipv6地址，如果你的服务器没有ipv6地址的话就允悲

**Comment by Li6lac** [comment]
> 谷歌学术ban了你的VPS的ipv4，在服务器的host里面加上谷歌学术的ipv6地址，如果你的服务器没有ipv6地址的话就允悲

我设置了ipv6还是一样被禁止访问。不知道原因

**Comment by Li6lac** [comment]
已解决。换了加速方式和IP。不需要绑定IPV6就可以用，大概率是机房的问题，也有人说是加速方式的问题。
