### ISSUE TITLE
vmess+http2 over tls 不支持h5ai脚本了？

### ISSUE THREAD

**Issue by nemo2018** [wulabing/V2Ray_ws-tls_bash_onekey#29]
vmess+http2 over tls 安装配置工作都正常了。
想在安装你的h5ai那个脚本，悲剧了。
![image](https://user-images.githubusercontent.com/37334053/38916644-c736f844-431a-11e8-8253-b6777cff42c9.png)

**Comment by nemo2018** [comment]
h2 win64客户端运行的不错，没断流。
但是Kitsunebi还支持的不好，太新了？

**Comment by wulabing** [comment]
H2这个目前应该是没法用website伪装了。除非h2放在非443端口上。但是这样好像也没意义了
或者可以用caddy配合实现，

**Comment by wulabing** [comment]
原先三件套的断流 有可能是core本身的原因，但是具体的也不清楚，有人反映断流的情况，但是作者也没有回复，就一直搁在那了

**Comment by dylanbai8** [comment]
"timeout": 600 会好一点， 我这里总是大概晚6点-9点固定时间段断流 白天基本不会 可能不是v2ray的问题

**Comment by ColeHou** [comment]
请问你们用这个h2的脚本是可以用的吗？我的用mac无法配置，我自己编译的源码，有http/2的选项，有老哥用过吗

**Comment by nemo2018** [comment]
core 3.22 说修正了一个断流的问题，现在断流问题解决了么？
