### ISSUE TITLE
域名dns解析IP 与 本机IP 不匹配 是否继续安装？

### ISSUE THREAD

**Issue by zijie98** [wulabing/V2Ray_ws-tls_bash_onekey#3]
域名dns解析IP 与 本机IP 不匹配 是否继续安装？（y/n）,请问怎么解决啊，谷歌云

**Comment by wulabing** [comment]
GCE 的机器应该是通过公网IP映射到内网的。所以进行匹配时获取的本机IP是内网IP，使用时只要确认你的域名解析到了你的服务器公网IP上，并继续安装即可

**Comment by zijie98** [comment]
是的，选继续
