### ISSUE TITLE
已经搭建成功，就是连不上，一直提示如下错误代码，懂得朋友帮忙看看，非常感谢!（AWS EC2服务器）

### ISSUE THREAD

**Issue by nihaohani** [wulabing/V2Ray_ws-tls_bash_onekey#311]
2021/01/23 11:23:58 [Warning] [3837506640] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: failed to dial to tcp:www.XXXXXX.cyou:29144 > Put "https://www.XXXXXX.cyou:29144/8167bb50283d/": dial tcp 13.XX.XXX.X:29144: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by PDSCi996** [comment]
感觉是不是你的vps相应的端口没有打开。

**Comment by nihaohani** [comment]
> 感觉是不是你的vps相应的端口没有打开。

![PNG](https://user-images.githubusercontent.com/50644202/105568011-411c6680-5d71-11eb-8534-a354b947e40f.PNG)
![0](https://user-images.githubusercontent.com/50644202/105568013-48437480-5d71-11eb-8710-1acc4fd74e7f.PNG)
出站入站都打开了
