### ISSUE TITLE
请问能不能指定升级到某版本

### ISSUE THREAD

**Issue by nemo2018** [wulabing/V2Ray_ws-tls_bash_onekey#32]
执行： bash <(curl -L -s https://install.direct/go.sh) 会升级到最新版，但是客户端总是不可能跟版本升级跟的那么紧，总是比服务器低一点。然后又要求客户端版本>=服务器。
这样实质就是没办法升级服务器了。

**Comment by nemo2018** [comment]
bash <(curl -L -s https://install.direct/go.sh --version v3.xx) 这样可以么？

**Comment by nemo2018** [comment]
![image](https://user-images.githubusercontent.com/37334053/41340662-7f4ec5a2-6f2a-11e8-8208-7b3ea6ab5f43.png)
有问题。

**Comment by wulabing** [comment]
后续版本会加入手动指定内核版本的功能。请等待更新
