### ISSUE TITLE
关于ws lts 脚本问题

### ISSUE THREAD

**Issue by ntgeralt** [wulabing/V2Ray_ws-tls_bash_onekey#33]
我看了下
nginx_conf_add(){
    touch ${nginx_conf_dir}/v2ray.conf
    cat>${nginx_conf_dir}/v2ray.conf<<EOF
    server {
        listen 443 ssl http2;
        ssl on;
        ssl_certificate       /etc/v2ray/v2ray.crt;
        ssl_certificate_key   /etc/v2ray/v2ray.key;
        ssl_protocols         TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

listen 443 ssl http2这里为何是http2

**Comment by ntgeralt** [comment]
我apt-get update 后的安装的nginx版本还是比较旧的1.6.2，似乎无法支持http/2。使用您的脚本最后提示nginx无法启动...

**Comment by wulabing** [comment]
已记录，请等待后续版本修复

**Comment by yun2673436976** [comment]
> 我看了下
> nginx_conf_add(){
> touch ${nginx_conf_dir}/v2ray.conf
> cat>${nginx_conf_dir}/v2ray.conf<<EOF
> server {
> listen 443 ssl http2;
> ssl on;
> ssl_certificate /etc/v2ray/v2ray.crt;
> ssl_certificate_key /etc/v2ray/v2ray.key;
> ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
> 
> listen 443 ssl http2这里为何是http2

请问你是输入什么命令看到这些代码，我是萌新有很多地方不懂，不吝赐教
