### ISSUE TITLE
Google云(GCE)安装时发生的80端口被占用问题

### ISSUE THREAD

**Issue by psyvirgin** [wulabing/V2Ray_ws-tls_bash_onekey#5]
我在google cloud上安装你的一键脚本的时候发现一个问题
系统环境 ubuntu 16.04.执行一键脚本的时候提示80端口被占用，新的虚拟机，未安装其他软件。

netstat -anp | grep 80
pe -ef | grep 80
lsof -i 80
都没有输出
在看脚本的时候发现，此处有代码
port_exist_check 80
port_exist_check ${port}
我把第一句删除了然后执行，发现可以了
如果其他同学出现类似的情况可以试试

**Comment by nemo5175747** [comment]
附上我的v2log

cat v2log.txt
[OK]  当前用户是root用户，进入安装流程  
[OK]  当前系统为 Debian 9  
Get:1 http://packages.cloud.google.com/apt cloud-sdk-stretch InRelease [6,377 B]
Get:2 http://security.debian.org stretch/updates InRelease [63.0 kB]
Ign:3 http://deb.debian.org/debian stretch InRelease
Get:4 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:5 http://security.debian.org stretch/updates/main Sources [123 kB]
Get:6 http://packages.cloud.google.com/apt google-compute-engine-stretch-stable InRelease [3,843 B]
Get:7 http://security.debian.org stretch/updates/main amd64 Packages [336 kB]
Get:8 http://security.debian.org stretch/updates/main Translation-en [148 kB]
Hit:9 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch InRelease
Get:10 http://packages.cloud.google.com/apt cloud-sdk-stretch/main amd64 Packages [27.9 kB]
Get:11 http://packages.cloud.google.com/apt google-compute-engine-stretch-stable/main amd64 Packages [1,125 B]
Get:12 http://deb.debian.org/debian stretch-backports InRelease [91.8 kB]
Hit:13 http://deb.debian.org/debian stretch Release
Get:15 http://deb.debian.org/debian stretch-backports/main Sources.diff/Index [27.8 kB]
Get:16 http://deb.debian.org/debian stretch-backports/main amd64 Packages.diff/Index [27.8 kB]
Get:17 http://deb.debian.org/debian stretch-backports/main Translation-en.diff/Index [27.8 kB]
Get:18 http://deb.debian.org/debian stretch-backports/main Sources 2018-02-28-0220.22.pdiff [31 B]
Get:19 http://deb.debian.org/debian stretch-backports/main Sources 2018-02-28-0820.44.pdiff [705 B]
Get:20 http://deb.debian.org/debian stretch-backports/main Sources 2018-02-28-1421.09.pdiff [33 B]
Get:21 http://deb.debian.org/debian stretch-backports/main Sources 2018-02-28-2023.03.pdiff [972 B]
Get:22 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-01-0821.08.pdiff [10.2 kB]
Get:23 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-01-1420.48.pdiff [983 B]
Get:24 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-01-2021.38.pdiff [31 B]
Get:25 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-02-2023.14.pdiff [651 B]
Get:26 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-03-0221.27.pdiff [33 B]
Get:27 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-04-0227.58.pdiff [1,587 B]
Get:27 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-04-0227.58.pdiff [1,587 B]
Get:28 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-02-28-0220.22.pdiff [1,414 B]
Get:29 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-02-28-1421.09.pdiff [288 B]
Get:30 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-02-28-2023.03.pdiff [202 B]
Get:31 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-03-01-0821.08.pdiff [6,578 B]
Get:32 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-03-01-1420.48.pdiff [748 B]
Get:33 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-03-01-2021.38.pdiff [417 B]
Get:34 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-03-03-0221.27.pdiff [230 B]
Get:35 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-03-04-0227.58.pdiff [1,165 B]
Get:36 http://deb.debian.org/debian stretch-backports/main Translation-en 2018-03-01-0821.08.pdiff [3,461 B]
Get:35 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-03-04-0227.58.pdiff [1,165 B]
Get:37 http://deb.debian.org/debian stretch-backports/main Translation-en 2018-03-04-0227.58.pdiff [396 B]
Get:37 http://deb.debian.org/debian stretch-backports/main Translation-en 2018-03-04-0227.58.pdiff [396 B]
Fetched 1,006 kB in 4s (237 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  ntpdate
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 72.4 kB of archives.
After this operation, 164 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 ntpdate amd64 1:4.2.8p10+dfsg-3+deb9u1 [72.4 kB]
Fetched 72.4 kB in 0s (1,194 kB/s)
Selecting previously unselected package ntpdate.
(Reading database ... 34268 files and directories currently installed.)
Preparing to unpack .../ntpdate_1%3a4.2.8p10+dfsg-3+deb9u1_amd64.deb ...
Unpacking ntpdate (1:4.2.8p10+dfsg-3+deb9u1) ...
Setting up ntpdate (1:4.2.8p10+dfsg-3+deb9u1) ...
Processing triggers for man-db (2.7.6.1-2) ...
[OK]  NTPdate 时间同步服务安装成功 
[信息]  正在进行时间同步 
 4 Mar 14:14:07 ntpdate[2450]: adjust time server 129.6.15.29 offset 0.007366 sec
[OK]  时间同步成功 
[OK]  当前系统时间 Sun, 04 Mar 2018 14:14:07 +0000（请注意时区间时间换算，换算后时间误差应为三分钟以内）
Reading package lists...
Building dependency tree...
Reading state information...
wget is already the newest version (1.18-5+deb9u1).
curl is already the newest version (7.52.1-5+deb9u4).
The following NEW packages will be installed:
  lsof
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 313 kB of archives.
After this operation, 451 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 lsof amd64 4.89+dfsg-0.1 [313 kB]
Fetched 313 kB in 0s (3,177 kB/s)
Selecting previously unselected package lsof.
(Reading database ... 34282 files and directories currently installed.)
Preparing to unpack .../lsof_4.89+dfsg-0.1_amd64.deb ...
Unpacking lsof (4.89+dfsg-0.1) ...
Setting up lsof (4.89+dfsg-0.1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Reading package lists...
Building dependency tree...
Reading state information...
cron is already the newest version (3.0pl1-128+b1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
[OK]  crontab 安装完成 
Reading package lists...
Building dependency tree...
Reading state information...
net-tools is already the newest version (1.60+git20161116.90da8a0-1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
[OK]  net-tools 安装完成 
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  bc
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 105 kB of archives.
After this operation, 238 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 bc amd64 1.06.95-9+b3 [105 kB]
Fetched 105 kB in 0s (1,539 kB/s)
Selecting previously unselected package bc.
(Reading database ... 34308 files and directories currently installed.)
Preparing to unpack .../bc_1.06.95-9+b3_amd64.deb ...
Unpacking bc (1.06.95-9+b3) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up bc (1.06.95-9+b3) ...
[OK]  bc 安装完成 
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  zip
The following NEW packages will be installed:
  unzip
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 170 kB of archives.
After this operation, 547 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 unzip amd64 6.0-21 [170 kB]
Fetched 170 kB in 0s (2,385 kB/s)
Selecting previously unselected package unzip.
(Reading database ... 34327 files and directories currently installed.)
Preparing to unpack .../unzip_6.0-21_amd64.deb ...
Unpacking unzip (6.0-21) ...
Processing triggers for mime-support (3.60) ...
Setting up unzip (6.0-21) ...
Processing triggers for man-db (2.7.6.1-2) ...
[OK]  unzip 安装完成 
[OK]  正在获取 公网ip 信息，请耐心等待 
域名dns解析IP：35.229.254.xxx
本机IP: 35.229.254.xxx
[OK]  域名dns解析IP  与 本机IP 匹配 
Installing V2Ray v3.11 on x86_64
Downloading V2Ray.
Extracting V2Ray package to /tmp/v2ray.
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /tmp/v2ray/v2ray-v3.11-linux-64/geoip.dat  
  inflating: /tmp/v2ray/v2ray-v3.11-linux-64/geosite.dat  
  inflating: /tmp/v2ray/v2ray-v3.11-linux-64/readme.md  
  inflating: /tmp/v2ray/v2ray-v3.11-linux-64/systemd/v2ray.service  
  inflating: /tmp/v2ray/v2ray-v3.11-linux-64/systemv/v2ray  
  inflating: /tmp/v2ray/v2ray-v3.11-linux-64/v2ctl  
  inflating: /tmp/v2ray/v2ray-v3.11-linux-64/v2ctl.sig  
  inflating: /tmp/v2ray/v2ray-v3.11-linux-64/v2ray  
  inflating: /tmp/v2ray/v2ray-v3.11-linux-64/v2ray.sig  
  inflating: /tmp/v2ray/v2ray-v3.11-linux-64/vpoint_socks_vmess.json  
  inflating: /tmp/v2ray/v2ray-v3.11-linux-64/vpoint_vmess_freedom.json  
PORT:12737
UUID:a742c757-a4d8-4f56-96ad-207a6c084bbd
V2Ray v3.11 is installed.
[OK]  V2ray 安装成功 
[错误]  80 端口被占用，请检查占用进程 结束后重新运行脚本

**Comment by wulabing** [comment]
目前定性为bug，不过通过当前的日志无法找到原因，请等待代码复查结果。


**无限期推迟修复**
**本issue寻求更多相关信息**

**Comment by psyvirgin** [comment]
不好意思，最近没上来看，那台服务器我给delete了，看不到日志，我重新开了台Debian 8，试了下，还是一样到问题，然后我看了下你的安装脚本，和之前的脚本不一样，没有这两句了
port_exist_check 80
port_exist_check ${port}
之前是google engineer给我回复的，删除第一个代码就可以了 
系统尽快得到解决  - -

**Comment by wulabing** [comment]
port_exist_check 80
port_exist_check ${port}
这两句没有做变动（依然可以通过删除第一句解决问题），但是为了防止端口占用导致证书生成失败以及V2RAY无法运行，这样的检测是有必要的
可以麻烦您把新版本的log贴上来嘛

**Comment by psyvirgin** [comment]
给楼上一个解决方法，如果你确认你的80端口没啥程序占用
就直接把install.sh里的port_exist_check()函数直接注释或者删掉，就可以安装了，我的已经成功    - -#

**Comment by psyvirgin** [comment]
port_exist_check(){
    if [[ 0 -eq `lsof -i:"$1" | wc -l` ]];then
        echo -e "${OK} ${GreenBG} $1 端口未被占用 ${Font}"
        sleep 1
    else
        echo -e "${Error} ${RedBG} 检测到 $1 端口被占用，以下为 $1 端口占用信息 ${Font}"
        lsof -i:"$1"
        echo -e "${OK} ${GreenBG} 5s 后将尝试自动 kill 占用进程 ${Font}"
        sleep 5
        lsof -i:"$1" | awk '{print $2}'| grep -v "PID" | xargs kill -9
        echo -e "${OK} ${GreenBG} kill 完成 ${Font}"
        sleep 1
    fi
}
你这里没有
另外我的是给函数删掉装进去的，log应该不一样了，是否需要？

**Comment by psyvirgin** [comment]
另外，GCE的debian9它会自动kill占用的端口，让脚本继续执行，直到成功，不过我用一个假域名安装的，最后证书生成失败了   - -

**Comment by wulabing** [comment]
自动kill 是我在几分钟前新加进去的功能实现，主要是为了解决GCE的这个问题，那感觉应该没什么问题了，你在DB8下测试用的是从我这里git的最新版本的shell么

**Comment by psyvirgin** [comment]
是的
那应该没问题了，我上次跟google support联系，他们的意思是两端检测冲突了。

**Comment by wulabing** [comment]
我开了一台GCE的debian8做了测试，经过测试安装成功。

Google support 的回复是有问题的，端口检测没有冲突，80端口确实是被占用，以下是占用示例
```
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
google_cl 441 root    5u  IPv4  13240      0t0  TCP instance-1.c.youtube-php-193806.internal:52077->metadata.google.internal:http (CLOSE_WAIT)
google_cl 441 root    6u  IPv4  14659      0t0  TCP instance-1.c.youtube-php-193806.internal:52094->metadata.google.internal:http (ESTABLISHED)
google_ip 442 root    5u  IPv4  14197      0t0  TCP instance-1.c.youtube-php-193806.internal:52088->metadata.google.internal:http (ESTABLISHED)
google_ac 444 root    5u  IPv4  13285      0t0  TCP instance-1.c.youtube-php-193806.internal:52079->metadata.google.internal:http (ESTABLISHED)
```
但是这个占用即使忽略掉也并不会影响程序的成功安装，干脆就把这个占用kill掉好了，暂时看来也不会影响其他内容

## 问题已处理

**Comment by nemo5175747** [comment]
实测一切正常。
还是提示80被占然后马上一个kill就继续跑下去了。

**Comment by wulabing** [comment]
好的 感谢反馈

**Comment by nemo5175747** [comment]
hello 借宝地问一个相关又不太相关的问题。
@psyvirgin 同学问下你，你有没有觉得GCP下面v2如果对比纯vmess和纯ss，同样的客户端，同样的网络，同一台vps，反复试了好几次，都觉得vmess比ss慢好多，比如说公司wifi下用fast.com测ss，10M。vmess测还不到2M有时候甚至几百K。win客户端做相同测试也一样。刷推，看油管也是一样的感受。我没有其他的vps可测试了不知道是GCP的问题，还是什么其他问题。你有此感觉么？谢谢。

**Comment by 429463267** [comment]
@wulabing

我这几天都在为这个gcp的80端口占用问题头疼，kill -9 杀不死，开了nginx 80无法访问，防火墙全部关闭了。
![image](https://user-images.githubusercontent.com/12899262/43505097-624c43b4-9598-11e8-8f86-66774eeba72b.png)

请问怎么才可以解决？

**Comment by yun2673436976** [comment]
> 我遇到同样的问题，附上我的v2log
> 
> cat v2log.txt
> [OK] 当前用户是root用户，进入安装流程
> [OK] 当前系统为 Debian 9
> Get:1 http://packages.cloud.google.com/apt cloud-sdk-stretch InRelease [6,377 B]
> Get:2 http://security.debian.org stretch/updates InRelease [63.0 kB]
> Ign:3 http://deb.debian.org/debian stretch InRelease
> Get:4 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
> Get:5 http://security.debian.org stretch/updates/main Sources [123 kB]
> Get:6 http://packages.cloud.google.com/apt google-compute-engine-stretch-stable InRelease [3,843 B]
> Get:7 http://security.debian.org stretch/updates/main amd64 Packages [336 kB]
> Get:8 http://security.debian.org stretch/updates/main Translation-en [148 kB]
> Hit:9 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch InRelease
> Get:10 http://packages.cloud.google.com/apt cloud-sdk-stretch/main amd64 Packages [27.9 kB]
> Get:11 http://packages.cloud.google.com/apt google-compute-engine-stretch-stable/main amd64 Packages [1,125 B]
> Get:12 http://deb.debian.org/debian stretch-backports InRelease [91.8 kB]
> Hit:13 http://deb.debian.org/debian stretch Release
> Get:15 http://deb.debian.org/debian stretch-backports/main Sources.diff/Index [27.8 kB]
> Get:16 http://deb.debian.org/debian stretch-backports/main amd64 Packages.diff/Index [27.8 kB]
> Get:17 http://deb.debian.org/debian stretch-backports/main Translation-en.diff/Index [27.8 kB]
> Get:18 http://deb.debian.org/debian stretch-backports/main Sources 2018-02-28-0220.22.pdiff [31 B]
> Get:19 http://deb.debian.org/debian stretch-backports/main Sources 2018-02-28-0820.44.pdiff [705 B]
> Get:20 http://deb.debian.org/debian stretch-backports/main Sources 2018-02-28-1421.09.pdiff [33 B]
> Get:21 http://deb.debian.org/debian stretch-backports/main Sources 2018-02-28-2023.03.pdiff [972 B]
> Get:22 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-01-0821.08.pdiff [10.2 kB]
> Get:23 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-01-1420.48.pdiff [983 B]
> Get:24 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-01-2021.38.pdiff [31 B]
> Get:25 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-02-2023.14.pdiff [651 B]
> Get:26 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-03-0221.27.pdiff [33 B]
> Get:27 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-04-0227.58.pdiff [1,587 B]
> Get:27 http://deb.debian.org/debian stretch-backports/main Sources 2018-03-04-0227.58.pdiff [1,587 B]
> Get:28 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-02-28-0220.22.pdiff [1,414 B]
> Get:29 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-02-28-1421.09.pdiff [288 B]
> Get:30 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-02-28-2023.03.pdiff [202 B]
> Get:31 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-03-01-0821.08.pdiff [6,578 B]
> Get:32 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-03-01-1420.48.pdiff [748 B]
> Get:33 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-03-01-2021.38.pdiff [417 B]
> Get:34 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-03-03-0221.27.pdiff [230 B]
> Get:35 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-03-04-0227.58.pdiff [1,165 B]
> Get:36 http://deb.debian.org/debian stretch-backports/main Translation-en 2018-03-01-0821.08.pdiff [3,461 B]
> Get:35 http://deb.debian.org/debian stretch-backports/main amd64 Packages 2018-03-04-0227.58.pdiff [1,165 B]
> Get:37 http://deb.debian.org/debian stretch-backports/main Translation-en 2018-03-04-0227.58.pdiff [396 B]
> Get:37 http://deb.debian.org/debian stretch-backports/main Translation-en 2018-03-04-0227.58.pdiff [396 B]
> Fetched 1,006 kB in 4s (237 kB/s)
> Reading package lists...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> The following NEW packages will be installed:
> ntpdate
> 0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
> Need to get 72.4 kB of archives.
> After this operation, 164 kB of additional disk space will be used.
> Get:1 http://deb.debian.org/debian stretch/main amd64 ntpdate amd64 1:4.2.8p10+dfsg-3+deb9u1 [72.4 kB]
> Fetched 72.4 kB in 0s (1,194 kB/s)
> Selecting previously unselected package ntpdate.
> (Reading database ... 34268 files and directories currently installed.)
> Preparing to unpack .../ntpdate_1%3a4.2.8p10+dfsg-3+deb9u1_amd64.deb ...
> Unpacking ntpdate (1:4.2.8p10+dfsg-3+deb9u1) ...
> Setting up ntpdate (1:4.2.8p10+dfsg-3+deb9u1) ...
> Processing triggers for man-db (2.7.6.1-2) ...
> [OK] NTPdate 时间同步服务安装成功
> [信息] 正在进行时间同步
> 4 Mar 14:14:07 ntpdate[2450]: adjust time server 129.6.15.29 offset 0.007366 sec
> [OK] 时间同步成功
> [OK] 当前系统时间 Sun, 04 Mar 2018 14:14:07 +0000（请注意时区间时间换算，换算后时间误差应为三分钟以内）
> Reading package lists...
> Building dependency tree...
> Reading state information...
> wget is already the newest version (1.18-5+deb9u1).
> curl is already the newest version (7.52.1-5+deb9u4).
> The following NEW packages will be installed:
> lsof
> 0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
> Need to get 313 kB of archives.
> After this operation, 451 kB of additional disk space will be used.
> Get:1 http://deb.debian.org/debian stretch/main amd64 lsof amd64 4.89+dfsg-0.1 [313 kB]
> Fetched 313 kB in 0s (3,177 kB/s)
> Selecting previously unselected package lsof.
> (Reading database ... 34282 files and directories currently installed.)
> Preparing to unpack .../lsof_4.89+dfsg-0.1_amd64.deb ...
> Unpacking lsof (4.89+dfsg-0.1) ...
> Setting up lsof (4.89+dfsg-0.1) ...
> Processing triggers for man-db (2.7.6.1-2) ...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> cron is already the newest version (3.0pl1-128+b1).
> 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
> [OK] crontab 安装完成
> Reading package lists...
> Building dependency tree...
> Reading state information...
> net-tools is already the newest version (1.60+git20161116.90da8a0-1).
> 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
> [OK] net-tools 安装完成
> Reading package lists...
> Building dependency tree...
> Reading state information...
> The following NEW packages will be installed:
> bc
> 0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
> Need to get 105 kB of archives.
> After this operation, 238 kB of additional disk space will be used.
> Get:1 http://deb.debian.org/debian stretch/main amd64 bc amd64 1.06.95-9+b3 [105 kB]
> Fetched 105 kB in 0s (1,539 kB/s)
> Selecting previously unselected package bc.
> (Reading database ... 34308 files and directories currently installed.)
> Preparing to unpack .../bc_1.06.95-9+b3_amd64.deb ...
> Unpacking bc (1.06.95-9+b3) ...
> Processing triggers for man-db (2.7.6.1-2) ...
> Setting up bc (1.06.95-9+b3) ...
> [OK] bc 安装完成
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Suggested packages:
> zip
> The following NEW packages will be installed:
> unzip
> 0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
> Need to get 170 kB of archives.
> After this operation, 547 kB of additional disk space will be used.
> Get:1 http://deb.debian.org/debian stretch/main amd64 unzip amd64 6.0-21 [170 kB]
> Fetched 170 kB in 0s (2,385 kB/s)
> Selecting previously unselected package unzip.
> (Reading database ... 34327 files and directories currently installed.)
> Preparing to unpack .../unzip_6.0-21_amd64.deb ...
> Unpacking unzip (6.0-21) ...
> Processing triggers for mime-support (3.60) ...
> Setting up unzip (6.0-21) ...
> Processing triggers for man-db (2.7.6.1-2) ...
> [OK] unzip 安装完成
> [OK] 正在获取 公网ip 信息，请耐心等待
> 域名dns解析IP：35.229.254.xxx
> 本机IP: 35.229.254.xxx
> [OK] 域名dns解析IP 与 本机IP 匹配
> Installing V2Ray v3.11 on x86_64
> Downloading V2Ray.
> Extracting V2Ray package to /tmp/v2ray.
> Archive: /tmp/v2ray/v2ray.zip
> inflating: /tmp/v2ray/v2ray-v3.11-linux-64/geoip.dat
> inflating: /tmp/v2ray/v2ray-v3.11-linux-64/geosite.dat
> inflating: /tmp/v2ray/v2ray-v3.11-linux-64/readme.md
> inflating: /tmp/v2ray/v2ray-v3.11-linux-64/systemd/v2ray.service
> inflating: /tmp/v2ray/v2ray-v3.11-linux-64/systemv/v2ray
> inflating: /tmp/v2ray/v2ray-v3.11-linux-64/v2ctl
> inflating: /tmp/v2ray/v2ray-v3.11-linux-64/v2ctl.sig
> inflating: /tmp/v2ray/v2ray-v3.11-linux-64/v2ray
> inflating: /tmp/v2ray/v2ray-v3.11-linux-64/v2ray.sig
> inflating: /tmp/v2ray/v2ray-v3.11-linux-64/vpoint_socks_vmess.json
> inflating: /tmp/v2ray/v2ray-v3.11-linux-64/vpoint_vmess_freedom.json
> PORT:12737
> UUID:a742c757-a4d8-4f56-96ad-207a6c084bbd
> V2Ray v3.11 is installed.
> [OK] V2ray 安装成功
> [错误] 80 端口被占用，请检查占用进程 结束后重新运行脚本

请问你这个日志怎么导出来的？萌新不太会。

**Comment by dylanbai8** [comment]
## 强行释放被占用的80端口
```
CMD=`lsof -i:"80" | awk '{print $1}' | grep -v "COMMAND" | sort -u` && systemctl disable ${CMD} && systemctl stop ${CMD} && killall -9 ${CMD}
```

**Comment by butiange** [comment]
> @wulabing
> 
> 我这几天都在为这个gcp的80端口占用问题头疼，kill -9 杀不死，开了nginx 80无法访问，防火墙全部关闭了。
> ![image](https://user-images.githubusercontent.com/12899262/43505097-624c43b4-9598-11e8-8f86-66774eeba72b.png)
> 
> 请问怎么才可以解决？

最近也碰到了这个问题，因为要安装caddy，结果80端口被占用，无法启动http server.请问最近解决了吗？

**Comment by liu-tongxue** [comment]
> > @wulabing
> > 我这几天都在为这个gcp的80端口占用问题头疼，kill -9 杀不死，开了nginx 80无法访问，防火墙全部关闭了。
> > ![image](https://user-images.githubusercontent.com/12899262/43505097-624c43b4-9598-11e8-8f86-66774eeba72b.png)
> > 请问怎么才可以解决？
> 
> 最近也碰到了这个问题，因为要安装caddy，结果80端口被占用，无法启动http server.请问最近解决了吗？

同问题+1
