### ISSUE TITLE
更改默认的443端口问题

### ISSUE THREAD

**Issue by zhanghewei-github** [wulabing/V2Ray_ws-tls_bash_onekey#52]
大佬您好，想请教下，国庆前可以正常访问，但国庆后突然访问不了，解析域名得知443端口国内已无法访问，但我按照脚本已经更改了端口，但还是解析出443端口出来，想问下还有哪个地方需要同步更改吗，十分感谢
截图如下
![image](https://user-images.githubusercontent.com/64525119/194796228-e30aa73d-0b0e-47d7-b153-f449fa7d4792.png)

**Comment by ilhuyi** [comment]
先在nginx.conf更换SSL端口，再在脚本设置里面更改成相同的端口，重启生效

**Comment by zhanghewei-github** [comment]
> 先在nginx.conf更换SSL端口，再在脚本设置里面更改成相同的端口，重启生效

大佬，还是不行，折腾了3天了跪求解疑，我更改为13141端口，但还是连接不了，ip跟端口都是通的，大佬方便加qq联系吗，qq号：915347198？（是因为还是443端口的原因吗？我的443端口用不了了）
v2rayN客户端提示：
2022/10/13 10:10:08 [Warning] [2594602550] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xx.xxx.xxx.xxx:13141/74558586df/): 502 Bad Gateway > websocket: bad handshake] > common/retry: all retry attempts failed
(备注：IP脱敏用x表示)
![image](https://user-images.githubusercontent.com/64525119/195483555-e84b154b-0333-41b5-88bc-dc4295f66687.png)
