### ISSUE TITLE
v2ray_ins.log在哪？

### ISSUE THREAD

**Issue by qq253044370** [wulabing/V2Ray_ws-tls_bash_onekey#54]
一键安装好以后，在xshell里并没有发现任何错误。按照安装完后，给的配置文件。用任何设备都无法FQ，手机端，路由端，电脑端都不行。用的都是全局模式
1、没有开启cdn，是灰色云朵。
2、直接访问域名，网站在播放音乐，这按理说nginx反代正常啊。
3、电脑端v2ray内核也是用的最新的。
4、IP没有被墙，用kcp 可以正常使用v2ray。查tcp阻断也没事啊4个绿色对钩。
5、22 443 端口也都开着呢。
求大神给个思路，我该怎么排除到底问题出在哪了？

不知道哪里出错。然后看说明 让看v2ray_ins.log 。但是我小白。不知道这个文件在哪。
倒是能找到 v2ray和nginx的access.log 和 error.log

**Comment by wulabing** [comment]
h2脚本中提供下载的配置文件可能已经过时了，上一次更新并没有维护H2部分，可以尝试将配置手动填写到客户端中然后尝试连接

**Comment by wulabing** [comment]
v2ray_ins.log 默认情况下应该在 /root 目录下 这取决于你执行脚本时所在的目录

**Comment by wulabing** [comment]
> 2、直接访问域名，网站在播放音乐，这按理说nginx反代正常啊。

当前版本页面是计算器，这可能说明你使用的是老版本的脚本，请将机器重装， 重新下载脚本重新安装

**Comment by qq253044370** [comment]
非常感谢 您在百忙之中抽空回答 我的疑问 。我发现我装的是分支那个。就是头像是熊猫的那位。我刚刚才发现您这是原版。我重新安装了，但是遗憾的是域名ssl证书申请太多了次了。只好下个星期再试了。说是一个星期5次 。

**Comment by qq253044370** [comment]
> > 2、直接访问域名，网站在播放音乐，这按理说nginx反代正常啊。
> 
> 当前版本页面是计算器，这可能说明你使用的是老版本的脚本，请将机器重装， 重新下载脚本重新安装

非常感谢 您在百忙之中抽空回答 我的疑问 。我发现我装的是分支那个。就是头像是熊猫的那位。我刚刚才发现您这是原版。我重新安装了，但是遗憾的是域名ssl证书申请太多了次了。只好下个星期再试了。说是一个星期5次 。
