### ISSUE TITLE
想请教在ws+tls+nginx反代的配置下如何使用国内服务器进行流量中转

### ISSUE THREAD

**Issue by wyx12840152** [wulabing/V2Ray_ws-tls_bash_onekey#55]
使用了大神您的一键脚本，完美运行，目前手上还有一台香港的小鸡，延迟不错，想用nginx进行流量中转，用proxy pass到v2ray主机，location是v2ray主机上配置的路径，还是不通。
我的想法是国内的客户端都经由我香港的小鸡然后再连接cloudflare的CDN。还请大神指教。
感谢。

**Comment by wulabing** [comment]
由于没有实际的操作经验，本人并不能帮助您解决这个问题，你可以尝试国内服务器使用 Nginx 四层 正向代理 看看是否能够实现你的需求，如果不可行的话，也可以尝试使用 haproxy 这样的工具实现 中继代理。

**Comment by Veryoldfish** [comment]
用BandwagonHost的VPS，加DNS混淆，实现国内看NetFlix，用的HTTP+WS+TLS的脚本，但是有一个小问题Nginx没有设置自动启动，第一次VPS作Snapshot的时候排查了一刻钟……发现怎么少了监听443端口……
-_-|||
用BandwagonHost的CentOS7 with BBR的image，配合KOOLshare开BBR，在华东地区测速到900MB/s的网速…… 可以说非常疯狂了……

**Comment by GHinStyle** [comment]
我觉得用nginx直接转发 不安全吧
应该可以用v2ray ws tls 在两台服务器间路由转发，甚至负载均衡。

**Comment by chengziqaq** [comment]
> 用BandwagonHost的VPS，加DNS混淆，实现国内看NetFlix，用的HTTP+WS+TLS的脚本，但是有一个小问题Nginx没有设置自动启动，第一次VPS作Snapshot的时候排查了一刻钟……发现怎么少了监听443端口……
> -_-|||
> 用BandwagonHost的CentOS7 with BBR的image，配合KOOLshare开BBR，在华东地区测速到900MB/s的网速…… 可以说非常疯狂了……

这个怎么设置的
