### ISSUE TITLE
手机端提示connection closed by pee

### ISSUE THREAD

**Issue by asdfcjf** [wulabing/V2Ray_ws-tls_bash_onekey#59]
电脑是正常的 手机不行 这是问什么 v2ray core是最新版本

**Comment by wulabing** [comment]
有可能是 core 太新 移动端跟进不及时导致的，在可用的情况下不建议频繁更新后端内核版本，电脑可用说明服务端无异常

**Comment by asdfcjf** [comment]
你是说哪个core APP 还是电脑 我APP都没更新版本 之前是可以的

**Comment by asdfcjf** [comment]
我电脑端也没更新过 15天前安装的脚本 一开始以为 是电脑端的CORE太老  执行更新版本 提示最新

**Comment by wulabing** [comment]
指手机APP的core 由app开发者负责跟进更新的。

**Comment by asdfcjf** [comment]
那我怎么办 我APP没更新过版本啊 突然就提示这个了 请问大哥 怎么解决啊 大哥

**Comment by asdfcjf** [comment]
![image](https://user-images.githubusercontent.com/8454291/55127488-409def00-514b-11e9-9915-2e734434400d.png)

**Comment by asdfcjf** [comment]
我是这个版本

**Comment by wulabing** [comment]
手机客户端尽量用新版本，里面有core 更新的

**Comment by asdfcjf** [comment]
我手机端用新版本 也不行 v2rayNG BifrostV 都不行 大哥 这到底什么问题啊 大哥

**Comment by wulabing** [comment]
不用着急，如果实在不行可以尝试重新手动输入链接信息，还不行，可以尝试服务端重装。

**Comment by asdfcjf** [comment]
大哥 我就是手动输入的啊 是不是谷歌cloud要配置什么

**Comment by wulabing** [comment]
PC上可用基本可以说明服务端没问题 所以还是需要你自己排查客户端方面的错误

**Comment by asdfcjf** [comment]
我重装试试 谢谢你了

**Comment by asdfcjf** [comment]
重装正常了谢谢 之前没用nginx现在用nginx
