### ISSUE TITLE
这人在脚本里留了后门啊,大家谨慎使用

### ISSUE THREAD

**Issue by lovefov** [wulabing/V2Ray_ws-tls_bash_onekey#63]
在 install_h2.sh 的240 行, 用curl 把 客户端的配置文件发到服务器上
  json_addr=`curl --upload-file ${client_conf} https://transfer.sh/wulabing_${camouflage}_${UUID}.json`
把别人的登陆信息 传到你自己的服务器上去?

**Comment by mrrubiks** [comment]
有意思

**Comment by wulabing** [comment]
请在口吐芬芳前查阅一下 transfer.sh 是什么，不假思索的回复只会体现一个人的无知


Tieyun <notifications@github.com> 于 2019年5月23日周四 上午1:19写道：

**Comment by myworksfun** [comment]
transfer.sh 应该是个在线生产二维码的工具吧。

**Comment by dylanbai8** [comment]
兄弟啊，互联网上保存谨慎的对的，但是不加思考和验证就恶语伤人这样很没素质。
你自己百度一下 transfer.sh 普及一下基础知识。不要伤了好人的心，作者不易，且用且珍惜。

**Comment by mrrubiks** [comment]
请作者把这个issue关掉吧，作者辛苦了

**Comment by lovefov** [comment]
抱歉
