### ISSUE TITLE
请问如何多用户

### ISSUE THREAD

**Issue by tztnuaji** [wulabing/V2Ray_ws-tls_bash_onekey#67]
我在 /etc/v2ray/config.json 里添加了一个client，id是用网页生成的，但是我在软件里却无法使用

**Comment by tztnuaji** [comment]
是不是因为我修改的位置不对啊

**Comment by wulabing** [comment]
多用户部分暂时不提供更多支持哈 ：），自己稍微研究一下，主要是我自己没用v2都有一阵了，不知道都更新了什么

**Comment by abcfyk** [comment]
@wulabing 不用v2ray现在还有什么比较好的？

**Comment by wulabing** [comment]
> @wulabing 不用v2ray现在还有什么比较好的？

ss-libev with AEAD
