### ISSUE TITLE
nginx PID not readable 导致运行停止

### ISSUE THREAD

**Issue by CongAn** [wulabing/V2Ray_ws-tls_bash_onekey#68]
系统版本：CentOS 7

PID not readable 会导致 systemctl 定期关闭
```
asia-east2-c systemd[1]: PID file /var/run/nginx.pid not readable (yet?) after start.
```

nginx ssl deprecated 警告影响未知

<img width="744" alt="企业微信截图_03bb8778-8e5f-43b6-9ead-43e87e4fa668" src="https://user-images.githubusercontent.com/16128049/59168021-83763d00-8b66-11e9-9b96-83f4945e8127.png">

**Comment by wulabing** [comment]
ssl 参数废弃暂时不会影响启动
如果有修改过nginx的配置 ，请自行检查配置是否正确
