### ISSUE TITLE
Centos 7.6 连接报错，希望增加对TLS1.3的支持

### ISSUE THREAD

**Issue by johnnytsai26** [wulabing/V2Ray_ws-tls_bash_onekey#69]
我很喜欢这个一键脚本，如果是一级域名，默认证书是申请一年的。
但最近遇到一个小问题，如果是Centos7，运行了yum install以后，升级到了7.6，连接就报错。

还有一个期望，就是能支持TLS1.3。
我1个月前安装的，V2ray core已经是最新版本。 Nginx是1.17. OpenSSL是1.0.1。
据说V2ray从4.18.2开始就支持TLS1.3，但OpenSSL需要1.1.1以上。就升级了OpenSSL到1.1.1，然后在Nginx的配置里，增加了TLS1.3
"ssl_protocols         TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;"
但还是以TLS1.2连接，如果改成只用1.3：
"ssl_protocols         TLSv1.3;"就连接不上了。。。
希望以后可以默认就支持TLS1.3 ，非常感谢！

**Comment by allanyu18** [comment]
我猜是因为，虽然本地OpenSSL升级了，但Nginx还是built with OpenSSL 1.0.2k-fips，导致不支持 TLS1.3。
因为Nginx -V以后：
nginx version: nginx/1.17.0
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled

希望能够升级一下Nginx和OpenSSL，增加对TLS1.3的支持就完美了，谢谢。

**Comment by wulabing** [comment]
在 Centos7 上只能通过编译安装来实现 Nginx OpenSSL 的更新，所以如果想体验 TLS 1.3 的话，建议直接用 Debian9 或者 Ubuntu18.04 ，这样安装的 Nginx 直接就是支持 TLS 1.3 的

**Comment by johnnytsai26** [comment]
谢谢你的回复，如果在Debian9 或者 Ubuntu18.04上用现在的脚本，是否默认就支持TLS1.3了呢？谢谢。

**Comment by wulabing** [comment]
理论上是的，您可以尝试一下

**Comment by johnnytsai26** [comment]
好的，我试一下，谢谢。

**Comment by johnnytsai26** [comment]
刚刚在Ubuntu18.04测试了。
nginx version: nginx/1.17.1
built by gcc 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04)
**built with OpenSSL 1.1.0g**  2 Nov 2017 (**running with OpenSSL 1.1.1**  11 Sep 2018)
TLS SNI support enabled
Ubuntu18.04的openssl是1.1.1的，但脚本里安装的Nginx是OpenSSL 1.1.0g编译的，所以测试下来目前默认还不支持TLS1.3。
是否在脚本里升级一下Nginx的安装就可以了呢？
谢谢。

**Comment by wulabing** [comment]
Nginx 的版本是 mainline 最新版本，如果是这种情况，那只能手动编译安装 Nginx 并在编译时参数指定新兵本的 OpenSSL 的路径

**Comment by johnnytsai26** [comment]
谢谢，我刚才看了下脚本：
http://nginx.org/packages/mainline/ubuntu/ ${VERSION_CODENAME} nginx
也看到了是取得当前版本对应得Nginx版本。 看来目前只有手动再安装Nginx。
谢谢。

**Comment by johnnytsai26** [comment]
刚才又看了下资料，好像Ubuntu18.10对应的Nginx是用openssl 1.1.1 编译的，不过18.04升级到18.10看起来挺麻烦，而且命令升级报错。
准备再试下Debian9。

**Comment by johnnytsai26** [comment]
Debian9也是同样情况，看来Nginx的mainline版都是在openssl1.1.0基础上编译的。:(.

**Comment by abcfyk** [comment]
@johnnytsai26 可以参考一下，ubuntu19.04测试通过
https://github.com/abcfyk/impatriot/blob/master/v2ray/ws_nginx_tls_1.3.sh

**Comment by johnnytsai26** [comment]
谢谢，看到了。那个脚本是下载了 https://nginx.org/download/nginx-1.17.2.tar.gz 然后编译安装的。应该是可行。
