### ISSUE TITLE
GCP上安装提示域名DNS解析IP与本机IP不匹配

### ISSUE THREAD

**Issue by davidlauhn** [wulabing/V2Ray_ws-tls_bash_onekey#7]
gcp
debian buster
防火墙端口已开放

> 请输入你的域名信息(eg:www.wulabing.com):xxx.xxx
> [OK]  正在获取 公网ip 信息，请耐心等待 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    15    0    15    0     0     13      0 --:--:--  0:00:01 --:--:--    13
> 域名dns解析IP：35.xxx.xxx.xxx
> 本机IP: 162.xxx.xxx.xxx
> [错误]  请确保域名添加了正确的 A 记录，否则将无法正常使用 V2ray 
> [错误]  域名dns解析IP 与 本机IP 不匹配 是否继续安装？（y/n）

域名为cloudflare解析，DNS ONLY，本地windows端可以ping通，显示正确IP地址
其中的本机IP经查询为台湾cloudflare

测试另一个脚本没问题 - https://github.com/hijkpw/scripts/blob/master/ubuntu_install_v2ray.sh ，只是这个脚本用的是v2fly

**Comment by kebijuelun** [comment]
请输入你的域名信息(eg:www.wulabing.com):xxx.xxx 

请问这里的域名具体是指什么？目前我只有一个能利用 ip ssh 登录的服务器，之类域名可以直接写这个 ip 吗？

**Comment by skez45** [comment]
怎么解决的

**Comment by davidlauhn** [comment]
> 怎么解决的

可能是脚本某个版本的问题，换个脚本就行，或者换个版本也行
