### ISSUE TITLE
TLS 与Mux 之间区别

### ISSUE THREAD

**Issue by N214** [wulabing/V2Ray_ws-tls_bash_onekey#7]
谢谢作者，

本人有一个知识上的小问题，经过nginx web tls后发现网速明显下降，据说是TLS过程中握手导致的。
可如果在客户端上加mux协议，网速几乎与之前（裸vmess）相差无几，这是为什么？
还有的就是服务端的access log上之前都是走433端口的变成mux.cool:9527

谢谢大家

**Comment by wulabing** [comment]
您好，
TLS 和 mux 之间没有具体关联，具体内容请参考白话文教程
mux：https://toutyrater.github.io/advanced/mux.html
tls：https://toutyrater.github.io/advanced/tls.html

关于使用了nginx ws tls 速度下降的问题，本人在实际使用中并没有太遇到过（毕竟从使用V2Ray开始我就一直用这套方案）

关于开启了mux后感觉网速恢复，以及mux.cool:9527，我无法回答，请前往 V2ray-core 提交 issue 向其作者提出相关问题
