### ISSUE TITLE
[求助]移动端突然用不了

### ISSUE THREAD

**Issue by yuanzzi** [wulabing/V2Ray_ws-tls_bash_onekey#70]
PC端 v2rayN 一直使用正常
- 移动端IOS Shadowrocket ,之前还好好的，突然不能用了且 延迟测试<超时>
- 后来发现PC可以正常访问伪装站点，移动端访问不了伪装站点
- 于是把移动端地址项配置为具体ip和端口，延迟测试正常了，FQ还是不行

PC端 一直使用正常

vps升级为最新v2ray重启服务 无用
奇怪的是PC可以访问伪装站点，移动端访问不到，不知道和这个( Nginx?)有没有关系

求教 QAQ 怎么解决

**Comment by wulabing** [comment]
可以看看站点的证书是不是过期了，有可能代码本身存在一些问题，依然会导致证书续签失败。
当然 重装VPS 后重新安装也可以临时解决问题

**Comment by yuanzzi** [comment]
非常感谢回复；
之前用的debian9.9 + bbrPlus于是重装为debian8 
重新安装了目前看来解决了
不知道跟bbrPlus 有没有关系，所以现在没敢装bbrPlus

**Comment by wulabing** [comment]
这个和 bbr 没有关系，放心安装

**Comment by hyy34** [comment]
请问 小火箭怎么设置的！？？

**Comment by yuanzzi** [comment]
> 请问 小火箭怎么设置的！？？

 从V2rayN导出 URL 复制到手机 或者 生成二维码 手机扫码
实在不行照着把参数输入进去也行我记得
