### ISSUE TITLE
本机 IPV4 是一串 html 是什么原因？

### ISSUE THREAD

**Issue by lxxiyue** [wulabing/V2Ray_ws-tls_bash_onekey#70]
如图：
![CleanShot 2022-12-27 at 12 27 33@2x](https://user-images.githubusercontent.com/37166502/209611243-363925eb-873d-4faf-98a8-5133de36d69b.png)

**Comment by Libohan12** [comment]
一样的问题，如果是http地址就不会返回403错误

**Comment by Libohan12** [comment]
curl http://ip.gs

**Comment by pinoyentrepreneur** [comment]
谁能帮我们解决这个问题？我们被卡住！

**Comment by Libohan12** [comment]
建议使用这个，刚刚解决了这个问题 https://github.com/taurusni/V2ray_tls_ws
