### ISSUE TITLE
你好，请问v2ray的log信息是在哪个位置？

### ISSUE THREAD

**Issue by Args** [wulabing/V2Ray_ws-tls_bash_onekey#71]
/var/log/v2ray/access.log  我在config.json中吧loglevel调为debug，但是还是没有log信息出现，所以不知道如果我想查看请求的信息的话应该怎么做？

**Comment by wulabing** [comment]
您好，这个请参考 V2ray 的文档，本程序不会对 V2ray 程序本身的日志记录造成干预

**Comment by Args** [comment]
好的 谢谢

**Comment by cxy2333355** [comment]
请问如何查看所有的access log，我查看只能看到一小部分的
