### ISSUE TITLE
centos 7.6和ubuntu 18.04安装时都提示[错误]  SSL 证书生成失败

### ISSUE THREAD

**Issue by jelly0925** [wulabing/V2Ray_ws-tls_bash_onekey#73]
[32m[OK][0m [42;37m 当前用户是root用户，进入安装流程 [0m 
[32m[OK][0m [42;37m 当前系统为 Centos 7 Core [0m 
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.keystealth.org
 * elrepo-kernel: repos.lax-noc.com
 * extras: mirror.keystealth.org
 * updates: mirror.keystealth.org
Package ntpdate-4.2.6p5-28.el7.centos.x86_64 already installed and latest version
Nothing to do
[32m[OK][0m [42;37m 安装 NTPdate 时间同步服务  完成 [0m
[32m[信息][0m [42;37m 正在进行时间同步 [0m
25 Aug 07:45:03 ntpdate[777]: adjust time server 129.6.15.26 offset -0.001750 sec
[32m[OK][0m [42;37m 时间同步成功 [0m
[32m[OK][0m [42;37m 当前系统时间 Sun, 25 Aug 2019 07:45:03 +0800（请注意时区间时间换算，换算后时间误差应为三分钟以内）[0m
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.keystealth.org
 * elrepo-kernel: repos.lax-noc.com
 * extras: mirror.keystealth.org
 * updates: mirrors.sonic.net
Package wget-1.14-18.el7_6.1.x86_64 already installed and latest version
Package lsof-4.87-6.el7.x86_64 already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.keystealth.org
 * elrepo-kernel: repos.lax-noc.com
 * extras: mirror.keystealth.org
 * updates: mirrors.sonic.net
Package crontabs-1.11-6.20121102git.el7.noarch already installed and latest version
Nothing to do
[32m[OK][0m [42;37m 安装 crontab 完成 [0m
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.keystealth.org
 * elrepo-kernel: repos.lax-noc.com
 * extras: mirror.keystealth.org
 * updates: mirrors.sonic.net
Package bc-1.06.95-13.el7.x86_64 already installed and latest version
Nothing to do
[32m[OK][0m [42;37m 安装 bc 完成 [0m
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: linux.mirrors.es.net
 * elrepo-kernel: repos.lax-noc.com
 * extras: mirror.sfo12.us.leaseweb.net
 * updates: mirrors.sonic.net
Package unzip-6.0-19.el7.x86_64 already installed and latest version
Nothing to do
[32m[OK][0m [42;37m 安装 unzip 完成 [0m
[32m[OK][0m [42;37m 正在获取 公网ip 信息，请耐心等待 [0m
域名dns解析IP：x.x.x.x域名解析的的IP地址正确
本机IP: x.x.x.x域名解析的的IP地址正确
[32m[OK][0m [42;37m 域名dns解析IP  与 本机IP 匹配 [0m
[36mInstalling V2Ray v4.20.0 on x86_64[0m
[36mDownloading V2Ray: https://github.com/v2ray/v2ray-core/releases/download/v4.20.0/v2ray-linux-64.zip[0m
[36mExtracting V2Ray package to /tmp/v2ray.[0m
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /tmp/v2ray/config.json  
   creating: /tmp/v2ray/doc/
  inflating: /tmp/v2ray/doc/readme.md  
  inflating: /tmp/v2ray/geoip.dat    
  inflating: /tmp/v2ray/geosite.dat  
   creating: /tmp/v2ray/systemd/
  inflating: /tmp/v2ray/systemd/v2ray.service  
   creating: /tmp/v2ray/systemv/
  inflating: /tmp/v2ray/systemv/v2ray  
  inflating: /tmp/v2ray/v2ctl        
 extracting: /tmp/v2ray/v2ctl.sig    
  inflating: /tmp/v2ray/v2ray        
 extracting: /tmp/v2ray/v2ray.sig    
  inflating: /tmp/v2ray/vpoint_socks_vmess.json  
  inflating: /tmp/v2ray/vpoint_vmess_freedom.json  
[32mV2Ray v4.20.0 is installed.[0m
[32m[OK][0m [42;37m 安装 V2ray 完成 [0m
[32m[OK][0m [42;37m 443 端口未被占用 [0m
[32m[OK][0m [42;37m config.json 下载 完成 [0m
[32m[OK][0m [42;37m client.json 下载 完成 [0m
[32m[OK][0m [42;37m config.json 配置变更 完成 [0m
[32m[OK][0m [42;37m client.json 配置变更 完成 [0m
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.keystealth.org
 * elrepo-kernel: repos.lax-noc.com
 * extras: mirror.keystealth.org
 * updates: mirror.keystealth.org
Package socat-1.7.3.2-2.el7.x86_64 already installed and latest version
Package 2:nmap-ncat-6.40-16.el7.x86_64 already installed and latest version
Nothing to do
[32m[OK][0m [42;37m 安装 SSL 证书生成脚本依赖 完成 [0m
[Sun Aug 25 07:45:53 CST 2019] Installing from online archive.
[Sun Aug 25 07:45:53 CST 2019] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Sun Aug 25 07:45:53 CST 2019] Extracting master.tar.gz
[Sun Aug 25 07:45:53 CST 2019] Installing to /root/.acme.sh
[Sun Aug 25 07:45:53 CST 2019] Installed to /root/.acme.sh/acme.sh
[Sun Aug 25 07:45:53 CST 2019] Installing alias to '/root/.bashrc'
[Sun Aug 25 07:45:53 CST 2019] OK, Close and reopen your terminal to start using acme.sh
[Sun Aug 25 07:45:53 CST 2019] Installing alias to '/root/.cshrc'
[Sun Aug 25 07:45:53 CST 2019] Installing alias to '/root/.tcshrc'
[Sun Aug 25 07:45:53 CST 2019] Installing cron job
14 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
[Sun Aug 25 07:45:53 CST 2019] Good, bash is found, so change the shebang to use bash as preferred.
[Sun Aug 25 07:45:54 CST 2019] OK
[Sun Aug 25 07:45:54 CST 2019] Install success!
[32m[OK][0m [42;37m 安装 SSL 证书生成脚本 完成 [0m
[Sun Aug 25 07:45:55 CST 2019] Standalone mode.
[Sun Aug 25 07:45:55 CST 2019] Registering account
[31m[错误][0m [41;37m SSL 证书生成失败 [0m

**Comment by WoodyJay** [comment]
ubuntu16.04一样的问题，letsencrypt有问题？

**Comment by wulabing** [comment]
关闭 firewalld 后重试

**Comment by gz0007** [comment]
> 关闭 firewalld 后重试

关闭后再次试过在ubuntu 18.04下还是出现这个ssl证书生成失败的问题

**Comment by richars** [comment]
同样在ubuntu 18.04下出现这个错误，前面都没问题，就是在生成证书的时候报错

**Comment by richars** [comment]
找出问题在哪里了，除了ubuntu本身的防火墙设置外，还需要在cloud的面板中将相应端口放行。

**Comment by richars** [comment]
该问题可以关闭了^_^
