### ISSUE TITLE
为什么无法时间同步？

### ISSUE THREAD

**Issue by hyy34** [wulabing/V2Ray_ws-tls_bash_onekey#74]
banwagong，安装的纯净centos7 ，为什么无法时间同步呢？能是啥原因？

[OK]  安装 NTPdate 时间同步服务  完成 
[信息]  正在进行时间同步 
18 Sep 17:37:31 ntpdate[16330]: no server suitable for synchronization found
[错误]  时间同步失败，请检查ntpdate服务是否正常工作

**Comment by hyy34** [comment]
测试了各种办法，都未遂。。

**Comment by wulabing** [comment]
时间同步失败不会中断安装，自动同步失败，可以尝试手动设置

**Comment by fengzhongluo** [comment]
我的是因为已经安装了ntp服务导致的，希望作者考虑能够完善一下
