### ISSUE TITLE
能使用自己签名的证书吗

### ISSUE THREAD

**Issue by MicalKarl** [wulabing/V2Ray_ws-tls_bash_onekey#76]
目前使用cloud flare 代理流量， 但证书过期太恶心了，能使用自己签名的证书吗（cloud flare 那里设置证书为flexible）

**Comment by wulabing** [comment]
当然可以，但是需要你自己设置

**Comment by MicalKarl** [comment]
> 
> 
> 当然可以，但是需要你自己设置

那这样不用tls也行，干脆ws不是更好吗？

**Comment by MicalKarl** [comment]
@wulabing 我发现改成cloud flare设置成flexible的话，v2ray报301错误，改成full就正常了，头疼

**Comment by wulabing** [comment]
因为脚本里设置的后端配置中启用了TLS，如果不想使用tls，你需要手动修改他
