### ISSUE TITLE
[错误]  SSL 证书生成失败 

### ISSUE THREAD

**Issue by boparticle** [wulabing/V2Ray_ws-tls_bash_onekey#77]
[OK]  安装 SSL 证书生成脚本 完成 
[Fri Sep 20 18:45:11 UTC 2019] Standalone mode.
[Fri Sep 20 18:45:11 UTC 2019] Create account key ok.
[Fri Sep 20 18:45:11 UTC 2019] Registering account
[Fri Sep 20 18:45:13 UTC 2019] Register account Error: {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
[Fri Sep 20 18:45:13 UTC 2019] Please add '--debug' or '--log' to check more details.
[Fri Sep 20 18:45:13 UTC 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[错误]  SSL 证书生成失败 

麻烦看下是啥原因，用你的上一个ws+tls+nx的就一切顺利，都是用cloudflare解析，谢谢。

**Comment by wulabing** [comment]
上面说的其实已经很清楚了
当前IP申请的证书过多，申请证书的API有一些限制
https://letsencrypt.org/docs/rate-limits/

**Comment by boparticle** [comment]
这个明白是申请过多被限制，但是安装就在这终止了，接下来不知道应该怎么进行下去了，小白一个不好意思哈。

**Comment by boparticle** [comment]
你的一键脚本是我找了这么久最干净省事的了，上一个“ws+tls+nx”试了其他家方案无数都不行，你这一下就搞定了，真的非常感谢，现在想试下http/2方案，就是在生成证书这卡住了，不知咋解决，扒了无数网，欲哭无泪。

**Comment by boparticle** [comment]
发现好像是用caddy申请证书总是有问题，而nginx一下就搞定了，对于小白好惨啊！

**Comment by wulabing** [comment]
添加任意子域名的A记录 然后使用子域名

boparticle <notifications@github.com> 于 2019年9月21日周六 12:14写道：

**Comment by hxy493045049** [comment]
应该是以前用过别的一键脚本，那个脚本已经申请过证书了，要过一周才能重新申请

**Comment by boparticle** [comment]
cloudflare那啥也没动，我把vm重置了重装了这个一键脚本，一切正常了，但是连不上，查了发现域名不支持http/2，不知道是否cloudflare并不是真的http/2的原因导致的。
