### ISSUE TITLE
安装完之后网页403

### ISSUE THREAD

**Issue by Trevorer** [wulabing/V2Ray_ws-tls_bash_onekey#79]
按照您的步骤装完了，cloudflare那边也弄好了，也能正常连上网，我打开域名显示403 forbidden，这个正常吗？需要写一个真实的网站来伪装吗？还是不用？

**Comment by wulabing** [comment]
我不使用Cloudflare ，目前我无法对 CF 的配置提供帮助

**Comment by Trevorer** [comment]
我看了下nginx的日志，它一直报/home/wwwroot/sCals/index.html  is forbidden   (13: permission denied)和open( )  /home/wwwroot/sCals/favico.ico failed (2: NO such file or directory)

**Comment by Trevorer** [comment]
原来是SELinux没有关闭，关闭了就正常了，可以把这个计算器换成其他网站模板吗？
