### ISSUE TITLE
增加对IPV6的支持

### ISSUE THREAD

**Issue by cchhuuaann1** [wulabing/V2Ray_ws-tls_bash_onekey#83]
本地小鸡有IPV6地址 是IPV4+IPV6双栈的小鸡 可否增加对IPV6的支持？不想浪费IPV6这个资源 而且IPV6方向的wall也比较弱鸡

**Comment by cchhuuaann1** [comment]
好像不是光修改nginx配置那么简单的 需要重新编译nginx -with-ipv6

**Comment by cchhuuaann1** [comment]
已解决 在/etc/nginx/conf.d/v2ray.conf 第一个server块里加    listen  [::]:443  ssl；   第二个第一个server块里加  listen  [::]:80；

**Comment by SunZhizhong** [comment]
好像还要修改V2RAY的配置文件"listen": "127.0.0.1"只会监听IPV4，需要修改成支持双栈的本地地址。

**Comment by cchhuuaann1** [comment]
> 好像还要修改V2RAY的配置文件"listen": "127.0.0.1"只会监听IPV4，需要修改成支持双栈的本地地址。

"listen":"::" 好像是改成这样

**Comment by liu191388548** [comment]
请问我以上两个都设置了 怎么不行呢 求指教

**Comment by liu191388548** [comment]
> 已解决 在/etc/nginx/conf.d/v2ray.conf 第一个server块里加 listen [::]:443 ssl； 第二个server块里加 listen [::]:80；

请问能贴出下 你是如何配置的么

**Comment by f2sky** [comment]
为什么提示安装成功了，但是 /etc/nginx/conf.d/v2ray.conf 这个配置里面是空白？

**Comment by KukiSa** [comment]
@f2sky This script supports IPv6. This script supports IPv6 by default when nginx and xray are used. If you find that IPv6 support cannot be achieved in practice, please try to attach detailed operation steps and necessary configuration files.
