### ISSUE TITLE
bug in port_exist_check function when deployed in gcp instance

### ISSUE THREAD

**Issue by yrong** [wulabing/V2Ray_ws-tls_bash_onekey#84]
`
➜  V2Ray_ws-tls_bash_onekey git:(master) ✗ lsof -i:80
COMMAND     PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
google_ac 14792  root    5u  IPv4  59241      0t0  TCP instance-4.asia-east2-a.c.liquid-optics-232113.internal:39728->metadata.google.internal:http (ESTABLISHED)

`

`
port_exist_check(){
    if [[ 0 -eq `lsof -i:"$1" | wc -l` ]];then
}
`
should fix by 
`
   if [[ 0 -eq `lsof -i:"$1" | **grep LISTEN** | wc -l` ]];then
`

**Comment by wulabing** [comment]
fixed
Thank you for your issue.You are able to pull request next time
