### ISSUE TITLE
建议加入BBR4合1加速功能，伪装网址的修改功能

### ISSUE THREAD

**Issue by reman-liao** [wulabing/V2Ray_ws-tls_bash_onekey#89]
如题

**Comment by reman-liao** [comment]
伪装都计算器程序，已经挂了，大神请设置一下，能自己改伪装网址的功能，方便更好伪装

**Comment by wulabing** [comment]
1、bbr 加速功能不会整合，请自行找相应的脚本单独安装
2、伪装内容本身就支持修改，请自行查询相关资料进行变更
3、根据封禁原理的推测，请不要用安装过SSR后端的机器安装V2ray

**Comment by reman-liao** [comment]
就是因为找不到哪里改啊，如果知道，就不请教您了

**Comment by Trevorer** [comment]
计算器的目录是/home/wwwroot/sCalc，可以自行替换其他网站模板

**Comment by reman-liao** [comment]
谢谢，收到

**Comment by yu412786485** [comment]
> 谢谢，收到

请问一下这个要怎么修改目录下的文件啊，我之前只用过ssr，我也在查怎么才能够更改伪装内容

**Comment by Ironieser** [comment]
> > 谢谢，收到
> 
> 请问一下这个要怎么修改目录下的文件啊，我之前只用过ssr，我也在查怎么才能够更改伪装内容
使用支持ftp的软件，直接可以修改
