### ISSUE TITLE
如何更改UUID

### ISSUE THREAD

**Issue by liu839611980** [wulabing/V2Ray_ws-tls_bash_onekey#90]

**Comment by wulabing** [comment]
配置文件位置：/etc/v2ray/config.json

修改里面的 UUID 后 **重启V2ray服务端**
UUID 有在线生成工具，自行查找

**Comment by liu839611980** [comment]
谢谢您，祝您事业顺利，事事顺心！




------------------ 原始邮件 ------------------
发件人: "wulabing"<notifications@github.com>;
发送时间: 2019年9月28日(星期六) 上午10:38
收件人: "wulabing/V2Ray_ws-tls_bash_onekey"<V2Ray_ws-tls_bash_onekey@noreply.github.com>;
抄送: "839611980"<839611980@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [wulabing/V2Ray_ws-tls_bash_onekey] 如何更改UUID (#90)




配置文件位置：/etc/v2ray/config.json
 
修改里面的 UUID 后 重启V2ray服务端
 UUID 有在线生成工具，自行查找
