### ISSUE TITLE
为什么使用安卓V2rayNG 连接不了

### ISSUE THREAD

**Issue by LizhenQiangCOOL** [wulabing/V2Ray_ws-tls_bash_onekey#92]
为什么使用安卓V2rayNG 连接不了

使用电脑就没问题

**Comment by Zerodot-v** [comment]
同问，电脑可以使用，手机就不行

**Comment by wulabing** [comment]
请尝试手动添加节点信息至手机客户端

Zerodot-v <notifications@github.com> 于 2019年10月2日周三 11:49写道：

**Comment by varequan** [comment]
手动添加节点后同样无法用V2rayNG客户端连接

**Comment by cchhuuaann1** [comment]
这是一个很奇怪的BUG 我也遇到过 只有在debian8下安装安卓WIN都能用 centos7.6 debian10安装完后就只能在WIN下用

**Comment by AndrewGoal** [comment]
我观察到V2rayNG好像获取不到手机VPN权限，我试了两台安卓手机都是这样，大家可以试试bifrostV，看看是不是V2rayNG的问题

**Comment by cchhuuaann1** [comment]
> 我观察到V2rayNG好像获取不到手机VPN权限，我试了两台安卓手机都是这样，大家可以试试bifrostV，看看是不是V2rayNG的问题

同一个脚本 在debian8下安卓就能使用 在debian10下就有问题 应该不是V2rayNG的问题 好像是nginx的问题

**Comment by LizhenQiangCOOL** [comment]
bifrostV我之前就一直使用它，无奈有广告；我觉得 V2rayNG没有问题，可能是客户端配置的问题（可以尝试更改下伪装类型为http），当然也有可能是其他问题，比如ngnix。 我现在Debian9，V2rayNg能使用了。

**Comment by cchhuuaann1** [comment]
> bifrostV我之前就一直使用它，无奈有广告；我觉得 V2rayNG没有问题，可能是客户端配置的问题（可以尝试更改下伪装类型为http），当然也有可能是其他问题，比如ngnix。 我现在Debian9，V2rayNg能使用了。

在V2连不上的时候我去查看了下服务的状态 经常是nginx Failed 然后重新启动nginx服务后就又能连上了

**Comment by waxy955** [comment]
同问，非常无语，主要在手机端用，只能不带tls了
