### ISSUE TITLE
速度问题

### ISSUE THREAD

**Issue by LizhenQiangCOOL** [wulabing/V2Ray_ws-tls_bash_onekey#93]
脚本是个好脚本    为什么这脚本(Nginx 的 vmess+ws+tls)  比   vmess+kcp 慢那么多？

**Comment by wulabing** [comment]
实际上问题应该是为什么kcp比tcp要快，这个和kcp的原理有关，请查阅相关资料

LizhenQiangCOOL <notifications@github.com> 于 2019年10月2日周三 16:21写道：
