### ISSUE TITLE
问题：SSL证书生成失败

### ISSUE THREAD

**Issue by XXDNXB** [wulabing/V2Ray_ws-tls_bash_onekey#94]
[OK]  安装 SSL 证书生成脚本 完成 
[Wed Oct  2 06:14:38 EDT 2019] Standalone mode.
[Wed Oct  2 06:14:38 EDT 2019] Create account key ok.
[Wed Oct  2 06:14:38 EDT 2019] Registering account
[Wed Oct  2 06:14:39 EDT 2019] Registered
[Wed Oct  2 06:14:39 EDT 2019] ACCOUNT_THUMBPRINT='02V83yp10fSVybsGR7DeTNLtZMu4NZc2KF5jWSJKdtQ'
[Wed Oct  2 06:14:39 EDT 2019] Creating domain key
[Wed Oct  2 06:14:39 EDT 2019] The domain key is here: /root/.acme.sh/www.73s7.com_ecc/www.73s7.com.key
[Wed Oct  2 06:14:39 EDT 2019] Single domain='www.73s7.com'
[Wed Oct  2 06:14:39 EDT 2019] Getting domain auth token for each domain
[Wed Oct  2 06:14:40 EDT 2019] Getting webroot for domain='www.73s7.com'
[Wed Oct  2 06:14:41 EDT 2019] Verifying: www.73s7.com
[Wed Oct  2 06:14:41 EDT 2019] Standalone mode server
[Wed Oct  2 06:14:45 EDT 2019] www.73s7.com:Verify error:Fetching http://www.73s7.com/.well-known/acme-challenge/uTDazKNJqlI-qD3Pwe7YL-uD1rOgZqXW5xWil9rrUtQ: Error getting validation data
[Wed Oct  2 06:14:45 EDT 2019] Please add '--debug' or '--log' to check more details.
[Wed Oct  2 06:14:45 EDT 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[错误]  SSL 证书生成失败 

描述：前面运行都没问题，直到安装SSL证书时候报错，请麻烦大佬看一下是什么原因，谢谢！

**Comment by wulabing** [comment]
若为CentOS系统请在防火墙放行对应的端口（默认80 443）或关闭防火墙

XXDNXB <notifications@github.com> 于 2019年10月2日周三 18:25写道：
