### ISSUE TITLE
CentOS 8下已不提供 NTP软件包，会中断在安装NTP同步处。

### ISSUE THREAD

**Issue by imdong** [wulabing/V2Ray_ws-tls_bash_onekey#98]
Vultr 东京服务器，CentOS 8 系统。

另外，由于没有开放防火墙端口，会导致申请证书失败。

**Comment by wulabing** [comment]
好的，近期会更新，修复一些问题

青石 <notifications@github.com> 于2019年10月14日周一 上午11:36写道：
