### ISSUE TITLE
debian10  安装完后无法连接 nginx的问题

### ISSUE THREAD

**Issue by cchhuuaann1** [wulabing/V2Ray_ws-tls_bash_onekey#99]
![QQ截图20191016222634](https://user-images.githubusercontent.com/26471985/66928656-567ded80-f064-11e9-89ae-6f61ff3b5aff.png)

我又来了  debian10  安装完后无法连接 又是nginx的问题

[OK]  rc.local 配置 完成 
[OK]  Nginx 启动 完成 
[OK]  设置 Nginx 开机自启 完成 
[OK]  V2ray 启动 完成 
[OK]  设置 v2ray 开机自启 完成 
[OK]  cron 计划任务更新 完成 
root@debian:~# service nginx status
Unit nginx.service could not be found.

**Comment by wulabing** [comment]
编译安装的Nginx 我没添加 init.d 和 systemd 通过 /etc/nginx/sbin/nginx 启动 但是默认应该是启动的才对

**Comment by cchhuuaann1** [comment]
但是 它真的就不是默认启动  如果默认启动  我也不会来提issue了
